# > Netflix
DOMAIN-SUFFIX,fast.com
DOMAIN-SUFFIX,netflix.ca
DOMAIN-SUFFIX,netflix.com
DOMAIN-SUFFIX,netflix.net
DOMAIN-SUFFIX,netflixinvestor.com
DOMAIN-SUFFIX,netflixtechblog.com
DOMAIN-SUFFIX,nflxext.com
DOMAIN-SUFFIX,nflximg.com
DOMAIN-SUFFIX,nflximg.net
DOMAIN-SUFFIX,nflxsearch.net
DOMAIN-SUFFIX,nflxso.net
DOMAIN-SUFFIX,nflxvideo.net

DOMAIN-SUFFIX,netflixdnstest1.com
DOMAIN-SUFFIX,netflixdnstest2.com
DOMAIN-SUFFIX,netflixdnstest3.com
DOMAIN-SUFFIX,netflixdnstest4.com
DOMAIN-SUFFIX,netflixdnstest5.com
DOMAIN-SUFFIX,netflixdnstest6.com
DOMAIN-SUFFIX,netflixdnstest7.com
DOMAIN-SUFFIX,netflixdnstest8.com
DOMAIN-SUFFIX,netflixdnstest9.com
DOMAIN-SUFFIX,netflixdnstest10.com

DOMAIN-SUFFIX,amazonaws.com
DOMAIN-SUFFIX,akamaiedge.net

DOMAIN,netflix.com.edgesuite.net
  
DOMAIN-KEYWORD,netflixdnstest
DOMAIN-KEYWORD,dualstack.apiproxy-
DOMAIN-KEYWORD,dualstack.ichnaea-web-
DOMAIN-KEYWORD,apiproxy-device-prod-nlb-

IP-CIDR,23.246.0.0/18,no-resolve
IP-CIDR,37.77.184.0/21,no-resolve
IP-CIDR,38.72.126.0/24,no-resolve
IP-CIDR,45.57.0.0/17,no-resolve
IP-CIDR,64.120.128.0/17,no-resolve
IP-CIDR,66.197.128.0/17,no-resolve
IP-CIDR,69.53.224.0/19,no-resolve
IP-CIDR,103.87.204.0/22,no-resolve
IP-CIDR,108.175.32.0/20,no-resolve
IP-CIDR,185.2.220.0/22,no-resolve
IP-CIDR,185.9.188.0/22,no-resolve
IP-CIDR,192.173.64.0/18,no-resolve
IP-CIDR,198.38.96.0/19,no-resolve
IP-CIDR,198.45.48.0/20,no-resolve
IP-CIDR,208.75.76.0/22,no-resolve
IP-CIDR,34.210.42.111/32,no-resolve
IP-CIDR,52.89.124.203/32,no-resolve
IP-CIDR,54.148.37.5/32,no-resolve

IP-CIDR,8.8.8.8/32,no-resolve
IP-CIDR,8.8.4.4/32,no-resolve

# > Disney Plus
DOMAIN-SUFFIX,abc-studios.com
DOMAIN-SUFFIX,abc.com
DOMAIN-SUFFIX,edgedatg.com

DOMAIN-SUFFIX,bamgrid.com
DOMAIN-SUFFIX,dmed.technology

DOMAIN-SUFFIX,dtci.co
DOMAIN-SUFFIX,dtci.technology
DOMAIN-SUFFIX,espn.co.uk
DOMAIN-SUFFIX,espn.com
DOMAIN-SUFFIX,espn.net
DOMAIN-SUFFIX,espncdn.com
DOMAIN-SUFFIX,espnqa.com
DOMAIN-SUFFIX,watchespn.com
DOMAIN-SUFFIX,omtrdc.net

DOMAIN-SUFFIX,marvel.com
DOMAIN-SUFFIX,marvel10thanniversary.com
DOMAIN-SUFFIX,marveldimensionofheroes.com
DOMAIN-SUFFIX,marvelparty.net
DOMAIN-SUFFIX,marvelpinball.com
DOMAIN-SUFFIX,marvelsdoubleagent.com
DOMAIN-SUFFIX,marvelspotlightplays.com
DOMAIN-SUFFIX,marvelsuperheroseptember.com
DOMAIN-SUFFIX,marvelsuperwar.com
DOMAIN-SUFFIX,themarvelexperiencetour.com

DOMAIN-SUFFIX,natgeomaps.com
DOMAIN-SUFFIX,nationalgeographic.com
DOMAIN-SUFFIX,nationalgeographicpartners.com
DOMAIN-SUFFIX,ngeo.com

DOMAIN-SUFFIX,disney.asia
DOMAIN-SUFFIX,disney.co.jp
DOMAIN-SUFFIX,disney.co.kr
DOMAIN-SUFFIX,disney.com
DOMAIN-SUFFIX,disney.sg
DOMAIN-SUFFIX,20thcenturystudios.com.au
DOMAIN-SUFFIX,20thcenturystudios.com.br
DOMAIN-SUFFIX,20thcenturystudios.jp
DOMAIN-SUFFIX,adventuresbydisney.com
DOMAIN-SUFFIX,babble.com
DOMAIN-SUFFIX,babyzone.com
DOMAIN-SUFFIX,bamgrid.com
DOMAIN-SUFFIX,beautyandthebeastmusical.co.uk
DOMAIN-SUFFIX,dilcdn.com
DOMAIN-SUFFIX,disney-asia.com
DOMAIN-SUFFIX,disney-discount.com
DOMAIN-SUFFIX,disney-plus.net
DOMAIN-SUFFIX,disney-portal.my.onetrust.com
DOMAIN-SUFFIX,disney-studio.com
DOMAIN-SUFFIX,disney-studio.net
DOMAIN-SUFFIX,disney.my.sentry.io
DOMAIN-SUFFIX,disneyadsales.com
DOMAIN-SUFFIX,disneyarena.com
DOMAIN-SUFFIX,disneyaulani.com
DOMAIN-SUFFIX,disneybaby.com
DOMAIN-SUFFIX,disneycareers.com
DOMAIN-SUFFIX,disneychannelonstage.com
DOMAIN-SUFFIX,disneychannelroadtrip.com
DOMAIN-SUFFIX,disneycruisebrasil.com
DOMAIN-SUFFIX,disneyenconcert.com
DOMAIN-SUFFIX,disneyiejobs.com
DOMAIN-SUFFIX,disneyinflight.com
DOMAIN-SUFFIX,disneyinternational.com
DOMAIN-SUFFIX,disneyinternationalhd.com
DOMAIN-SUFFIX,disneyjunior.com
DOMAIN-SUFFIX,disneyjuniortreataday.com
DOMAIN-SUFFIX,disneylatino.com
DOMAIN-SUFFIX,disneymagicmomentsme.com
DOMAIN-SUFFIX,disneyme.com
DOMAIN-SUFFIX,disneymeetingsandevents.com
DOMAIN-SUFFIX,disneymovieinsiders.com
DOMAIN-SUFFIX,disneymusicpromotion.com
DOMAIN-SUFFIX,disneynewseries.com
DOMAIN-SUFFIX,disneynow.com
DOMAIN-SUFFIX,disneypeoplesurveys.com
DOMAIN-SUFFIX,disneyplus.bn5x.net
DOMAIN-SUFFIX,disneyplus.com
DOMAIN-SUFFIX,disneyplus.com.ssl.sc.omtrdc.net
DOMAIN-SUFFIX,disneyredirects.com
DOMAIN-SUFFIX,disneysrivieraresort.com
DOMAIN-SUFFIX,disneystore.com
DOMAIN-SUFFIX,disneystreaming.com
DOMAIN-SUFFIX,disneysubscription.com
DOMAIN-SUFFIX,disneytickets.co.uk
DOMAIN-SUFFIX,disneyturkiye.com.tr
DOMAIN-SUFFIX,disneytvajobs.com
DOMAIN-SUFFIX,disneyworld-go.com
DOMAIN-SUFFIX,dssott.com
DOMAIN-SUFFIX,go-disneyworldgo.com
DOMAIN-SUFFIX,go.com
DOMAIN-SUFFIX,mickey.tv
DOMAIN-SUFFIX,moviesanywhere.com
DOMAIN-SUFFIX,nomadlandmovie.ch
DOMAIN-SUFFIX,playmation.com
DOMAIN-SUFFIX,shopdisney.com
DOMAIN-SUFFIX,shops-disney.com
DOMAIN-SUFFIX,sorcerersarena.com
DOMAIN-SUFFIX,spaindisney.com
DOMAIN-SUFFIX,star-brasil.com
DOMAIN-SUFFIX,star-latam.com
DOMAIN-SUFFIX,starwars.com
DOMAIN-SUFFIX,starwarsgalacticstarcruiser.com
DOMAIN-SUFFIX,starwarskids.com
DOMAIN-SUFFIX,streamingdisney.net
DOMAIN-SUFFIX,thestationbymaker.com
DOMAIN-SUFFIX,thisispolaris.com
DOMAIN-SUFFIX,watchdisneyfe.com

DOMAIN-SUFFIX,braze.com
DOMAIN-SUFFIX,cdn.optimizely.com
DOMAIN-SUFFIX,cdn.registerdisney.go.com
DOMAIN-SUFFIX,cws.conviva.com
DOMAIN-SUFFIX,d9.flashtalking.com
DOMAIN-SUFFIX,disney.demdex.net
DOMAIN-SUFFIX,js-agent.newrelic.com
