# > CUS
DOMAIN-SUFFIX,hostloc.com
DOMAIN-SUFFIX,v2ex.com
DOMAIN-SUFFIX,deepl.com
DOMAIN-SUFFIX,letsencrypt.org
DOMAIN-SUFFIX,ampproject.org
DOMAIN,token.safebrowsing.apple
DOMAIN-SUFFIX,vhx.tv
DOMAIN-SUFFIX,vhx.com
DOMAIN-SUFFIX,gitcdn.xyz
DOMAIN-SUFFIX,gitcdn.link
DOMAIN-SUFFIX,secureservercdn.net
DOMAIN-SUFFIX,privnote.com

# > Apple
DOMAIN-SUFFIX,cdn-apple.com
DOMAIN-SUFFIX,mzstatic.com
DOMAIN-SUFFIX,aaplimg.com
DOMAIN-SUFFIX,apple.co
DOMAIN-SUFFIX,apple.com
DOMAIN-SUFFIX,icloud-content.com
DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,itunes.com
DOMAIN-SUFFIX,itunes.apple.com
DOMAIN-SUFFIX,lookup-api.apple.com
DOMAIN-SUFFIX,me.com

# > Twitter
DOMAIN-SUFFIX,ads-twitter.com
DOMAIN-SUFFIX,periscope.tv
DOMAIN-SUFFIX,pscp.tv
DOMAIN-SUFFIX,t.co
DOMAIN-SUFFIX,tellapart.com
DOMAIN-SUFFIX,tweetdeck.com
DOMAIN-SUFFIX,twimg.com
DOMAIN-SUFFIX,twitpic.com
DOMAIN-SUFFIX,twitter.com
DOMAIN-SUFFIX,twitter.jp
DOMAIN-SUFFIX,twitterinc.com
DOMAIN-SUFFIX,twitteroauth.com
DOMAIN-SUFFIX,twitterstat.us
DOMAIN-SUFFIX,twtrdns.net
DOMAIN-SUFFIX,twttr.com
DOMAIN-SUFFIX,vine.co

# > Telegram
DOMAIN-SUFFIX,comments.app
DOMAIN-SUFFIX,contest.com
DOMAIN-SUFFIX,graph.org
DOMAIN-SUFFIX,quiz.directory
DOMAIN-SUFFIX,t.me
DOMAIN-SUFFIX,tdesktop.com
DOMAIN-SUFFIX,telega.one
DOMAIN-SUFFIX,telegra.ph
DOMAIN-SUFFIX,telegram.dog
DOMAIN-SUFFIX,telegram.me
DOMAIN-SUFFIX,telegram.org
DOMAIN-SUFFIX,telegram.space
DOMAIN-SUFFIX,telesco.pe
DOMAIN-SUFFIX,tg.dev
DOMAIN-SUFFIX,tx.me
DOMAIN-SUFFIX,usercontent.dev

IP-CIDR,91.108.56.0/22,no-resolve
IP-CIDR,91.108.4.0/22,no-resolve
IP-CIDR,91.108.8.0/22,no-resolve
IP-CIDR,91.108.16.0/22,no-resolve
IP-CIDR,91.108.12.0/22,no-resolve
IP-CIDR,149.154.160.0/20,no-resolve
IP-CIDR,91.105.192.0/23,no-resolve
IP-CIDR,91.108.20.0/22,no-resolve
IP-CIDR,185.76.151.0/24,no-resolve
IP-CIDR6,2001:b28:f23d::/48,no-resolve
IP-CIDR6,2001:b28:f23f::/48,no-resolve
IP-CIDR6,2001:67c:4e8::/48,no-resolve
IP-CIDR6,2001:b28:f23c::/48,no-resolve
IP-CIDR6,2a0a:f280::/32,no-resolve

IP-CIDR,109.239.140.0/24,no-resolve
IP-CIDR,149.154.164.0/22,no-resolve
IP-CIDR,149.154.172.0/22,no-resolve
IP-CIDR,5.28.192.0/18,no-resolve

# > Youtube
DOMAIN-SUFFIX,youtube
DOMAIN-SUFFIX,ggpht.com
DOMAIN-SUFFIX,googlevideo.com
DOMAIN-SUFFIX,withyoutube.com
DOMAIN-SUFFIX,youtu.be
DOMAIN-SUFFIX,youtube-nocookie.com
DOMAIN-SUFFIX,youtube-ui.l.google.com
DOMAIN-SUFFIX,youtube.com
DOMAIN-SUFFIX,youtube.com.sg
DOMAIN-SUFFIX,youtube.sg
DOMAIN-SUFFIX,youtubeeducation.com
DOMAIN-SUFFIX,youtubefanfest.com
DOMAIN-SUFFIX,youtubegaming.com
DOMAIN-SUFFIX,youtubego.com
DOMAIN-SUFFIX,youtubekids.com
DOMAIN-SUFFIX,youtubemobilesupport.com
DOMAIN-SUFFIX,yt.be
DOMAIN-SUFFIX,ytimg.com
DOMAIN-SUFFIX,googleapis.com

# > Dropbox
DOMAIN-SUFFIX,db.tt
DOMAIN-SUFFIX,dropbox-dns.com
DOMAIN-SUFFIX,dropbox.com
DOMAIN-SUFFIX,dropbox.tech
DOMAIN-SUFFIX,dropboxapi.com
DOMAIN-SUFFIX,dropboxbusiness.com
DOMAIN-SUFFIX,dropboxcaptcha.com
DOMAIN-SUFFIX,dropboxforum.com
DOMAIN-SUFFIX,dropboxforums.com
DOMAIN-SUFFIX,dropboxinsiders.com
DOMAIN-SUFFIX,dropboxmail.com
DOMAIN-SUFFIX,dropboxpartners.com
DOMAIN-SUFFIX,dropboxstatic.com
DOMAIN-SUFFIX,dropboxusercontent.com
DOMAIN-SUFFIX,getdropbox.com

# > Github
DOMAIN-SUFFIX,npm.community
DOMAIN-SUFFIX,npmjs.com
DOMAIN-SUFFIX,npmjs.org
DOMAIN-SUFFIX,atom.io
DOMAIN-SUFFIX,dependabot.com
DOMAIN-SUFFIX,ghcr.io
DOMAIN-SUFFIX,git.io
DOMAIN-SUFFIX,github.blog
DOMAIN-SUFFIX,github.com
DOMAIN-SUFFIX,github.community
DOMAIN-SUFFIX,github.dev
DOMAIN-SUFFIX,github.io
DOMAIN-SUFFIX,githubapp.com
DOMAIN-SUFFIX,githubassets.com
DOMAIN-SUFFIX,githubhackathon.com
DOMAIN-SUFFIX,githubpreview.dev
DOMAIN-SUFFIX,githubstatus.com
DOMAIN-SUFFIX,githubuniverse.com
DOMAIN-SUFFIX,githubusercontent.com
DOMAIN-SUFFIX,myoctocat.com
DOMAIN-SUFFIX,opensource.guide
DOMAIN-SUFFIX,thegithubshop.com

# > Gitlab
DOMAIN-SUFFIX,gitlab.com
DOMAIN-SUFFIX,gitlab.io
DOMAIN-SUFFIX,gitlab.net
DOMAIN-SUFFIX,gitlab-static.net

# > GitBook
DOMAIN-SUFFIX,gitbook.com
DOMAIN-SUFFIX,gitbook.io

# > JSDelivr
DOMAIN-SUFFIX,jsdelivr.com
DOMAIN-SUFFIX,jsdelivr.net
DOMAIN-SUFFIX,esm.run

# > StackExchange
DOMAIN-SUFFIX,askubuntu.com
DOMAIN-SUFFIX,blogoverflow.com
DOMAIN-SUFFIX,codeforaliving.io
DOMAIN-SUFFIX,mathoverflow.net
DOMAIN-SUFFIX,serverfault.com
DOMAIN-SUFFIX,sstatic.net
DOMAIN-SUFFIX,stackapps.com
DOMAIN-SUFFIX,stackauth.com
DOMAIN-SUFFIX,stackexchange.com
DOMAIN-SUFFIX,stackmod.blog
DOMAIN-SUFFIX,stackoverflow.blog
DOMAIN-SUFFIX,stackoverflow.co
DOMAIN-SUFFIX,stackoverflow.com
DOMAIN-SUFFIX,stackoverflow.email
DOMAIN-SUFFIX,stackoverflowbusiness.com
DOMAIN-SUFFIX,stackoverflowcareers.com
DOMAIN-SUFFIX,stacksnippets.net
DOMAIN-SUFFIX,superuser.com
DOMAIN-SUFFIX,tex-talk.net
DOMAIN-SUFFIX,thesffblog.com

# > Python
DOMAIN-SUFFIX,pycon.org
DOMAIN-SUFFIX,pypa.io
DOMAIN-SUFFIX,pypi.io
DOMAIN-SUFFIX,pypi.org
DOMAIN-SUFFIX,python.org
DOMAIN-SUFFIX,pythonhosted.org
DOMAIN-SUFFIX,piwheels.org

# > Javascript
DOMAIN-SUFFIX,javascript.info

# > Wikimedia
DOMAIN-SUFFIX,mediawiki.org
DOMAIN-SUFFIX,wikibooks.org
DOMAIN-SUFFIX,wikidata.org
DOMAIN-SUFFIX,wikimediafoundation.org
DOMAIN-SUFFIX,wikimedia.org
DOMAIN-SUFFIX,wikinews.org
DOMAIN-SUFFIX,wikipedia.org
DOMAIN-SUFFIX,wikiquote.org
DOMAIN-SUFFIX,wikisource.org
DOMAIN-SUFFIX,wikiversity.org
DOMAIN-SUFFIX,wikivoyage.org
DOMAIN-SUFFIX,wiktionary.org
DOMAIN-SUFFIX,wmfusercontent.org
DOMAIN-SUFFIX,w.wiki
DOMAIN-SUFFIX,toolforge.org
DOMAIN-SUFFIX,wikimediacloud.org
DOMAIN-SUFFIX,wmcloud.org
DOMAIN-SUFFIX,wmflabs.org
  
# > wikiHow
DOMAIN-SUFFIX,wikihow.com

# > hCaptcha
DOMAIN-SUFFIX,botstop.com
DOMAIN-SUFFIX,hcaptcha.com
DOMAIN-SUFFIX,hcaptchastatus.com

# > Google
DOMAIN-SUFFIX,android.com
DOMAIN-SUFFIX,androidify.com

DOMAIN-SUFFIX,blogger.com
DOMAIN-SUFFIX,blogblog.com
DOMAIN-SUFFIX,blogspot.com
DOMAIN-SUFFIX,blogspot.sg

DOMAIN-SUFFIX,dart.dev
DOMAIN-SUFFIX,dartlang.org
DOMAIN-SUFFIX,dartpad.dev

DOMAIN-SUFFIX,fastlane.ci
DOMAIN-SUFFIX,fastlane.tools

DOMAIN-SUFFIX,flutter.dev
DOMAIN-SUFFIX,flutterapp.com

DOMAIN-SUFFIX,go-lang.com
DOMAIN-SUFFIX,go-lang.net
DOMAIN-SUFFIX,go-lang.org
DOMAIN-SUFFIX,go.dev
DOMAIN-SUFFIX,godoc.org
DOMAIN-SUFFIX,golang.com
DOMAIN-SUFFIX,golang.net
DOMAIN-SUFFIX,golang.org

DOMAIN-SUFFIX,charlestonroadregistry.com
DOMAIN-SUFFIX,registry.google
DOMAIN-SUFFIX,get.app
DOMAIN-SUFFIX,get.dev
DOMAIN-SUFFIX,get.how
DOMAIN-SUFFIX,get.page
DOMAIN-SUFFIX,iam.soy
DOMAIN-SUFFIX,xn--p8j9a0d9c9a.xn--q9jyb4c

DOMAIN,scholar.google.com
DOMAIN,scholar.google.com.sg
DOMAIN,scholar.l.google.com

DOMAIN-SUFFIX,pki.goog

DOMAIN-SUFFIX,kaggle.com
DOMAIN-SUFFIX,kaggle.io

DOMAIN-SUFFIX,deps.dev
DOMAIN-SUFFIX,deps.info
DOMAIN-SUFFIX,opensourceinsight.dev
DOMAIN-SUFFIX,opensourceinsights.dev

DOMAIN-SUFFIX,polymer-project.org
DOMAIN-SUFFIX,polymerproject.org

DOMAIN-SUFFIX,v8.dev
DOMAIN-SUFFIX,v8project.org

DOMAIN-SUFFIX,and
DOMAIN-SUFFIX,chrome
DOMAIN-SUFFIX,dclk
DOMAIN-SUFFIX,gbiz
DOMAIN-SUFFIX,gle
DOMAIN-SUFFIX,gmail
DOMAIN-SUFFIX,goo
DOMAIN-SUFFIX,goog
DOMAIN-SUFFIX,google
DOMAIN-SUFFIX,guge
DOMAIN-SUFFIX,hangout
DOMAIN-SUFFIX,nexus
DOMAIN-SUFFIX,xn--flw351e
DOMAIN-SUFFIX,xn--qcka1pmc
DOMAIN-SUFFIX,google.com
DOMAIN-SUFFIX,google.com.sg
DOMAIN-SUFFIX,0emm.com
DOMAIN-SUFFIX,1e100.net
DOMAIN-SUFFIX,1ucrs.com
DOMAIN-SUFFIX,466453.com
DOMAIN-SUFFIX,abc.xyz
DOMAIN-SUFFIX,adgoogle.net
DOMAIN-SUFFIX,admeld.com
DOMAIN-SUFFIX,angulardart.org
DOMAIN-SUFFIX,api.ai
DOMAIN-SUFFIX,apigee.com
DOMAIN-SUFFIX,appbridge.ca
DOMAIN-SUFFIX,appbridge.io
DOMAIN-SUFFIX,appbridge.it
DOMAIN-SUFFIX,appspot.com
DOMAIN-SUFFIX,apture.com
DOMAIN-SUFFIX,area120.com
DOMAIN-SUFFIX,asp-cc.com
DOMAIN-SUFFIX,autodraw.com
DOMAIN-SUFFIX,bandpage.com
DOMAIN-SUFFIX,baselinestudy.com
DOMAIN-SUFFIX,baselinestudy.org
DOMAIN-SUFFIX,bazel.build
DOMAIN-SUFFIX,bdn.dev
DOMAIN-SUFFIX,beatthatquote.com
DOMAIN-SUFFIX,blink.org
DOMAIN-SUFFIX,brocaproject.com
DOMAIN-SUFFIX,brotli.org
DOMAIN-SUFFIX,bumpshare.com
DOMAIN-SUFFIX,bumptop.ca
DOMAIN-SUFFIX,bumptop.com
DOMAIN-SUFFIX,bumptop.net
DOMAIN-SUFFIX,bumptop.org
DOMAIN-SUFFIX,bumptunes.com
DOMAIN-SUFFIX,campuslondon.com
DOMAIN-SUFFIX,certificate-transparency.org
DOMAIN-SUFFIX,chrome.com
DOMAIN-SUFFIX,chromebook.com
DOMAIN-SUFFIX,chromecast.com
DOMAIN-SUFFIX,chromeos.dev
DOMAIN-SUFFIX,chromium.org
DOMAIN-SUFFIX,chronicle.security
DOMAIN-SUFFIX,chroniclesec.com
DOMAIN-SUFFIX,cloudburstresearch.com
DOMAIN-SUFFIX,cloudfunctions.net
DOMAIN-SUFFIX,cloudproxy.app
DOMAIN-SUFFIX,cloudrobotics.com
DOMAIN-SUFFIX,cobrasearch.com
DOMAIN-SUFFIX,codespot.com
DOMAIN-SUFFIX,conscrypt.com
DOMAIN-SUFFIX,conscrypt.org
DOMAIN-SUFFIX,cookiechoices.org
DOMAIN-SUFFIX,coova.com
DOMAIN-SUFFIX,coova.net
DOMAIN-SUFFIX,coova.org
DOMAIN-SUFFIX,crossmediapanel.com
DOMAIN-SUFFIX,crr.com
DOMAIN-SUFFIX,cs4hs.com
DOMAIN-SUFFIX,dartsearch.net
DOMAIN-SUFFIX,dataliberation.org
DOMAIN-SUFFIX,debug.com
DOMAIN-SUFFIX,debugproject.com
DOMAIN-SUFFIX,deepmind.com
DOMAIN-SUFFIX,devsitetest.how
DOMAIN-SUFFIX,dialogflow.com
DOMAIN-SUFFIX,digitalassetlinks.org
DOMAIN-SUFFIX,episodic.com
DOMAIN-SUFFIX,feedburner.com
DOMAIN-SUFFIX,fflick.com
DOMAIN-SUFFIX,financeleadsonline.com
DOMAIN-SUFFIX,firebaseapp.com
DOMAIN-SUFFIX,firebaseio.com
DOMAIN-SUFFIX,foofle.com
DOMAIN-SUFFIX,froogle.com
DOMAIN-SUFFIX,fuchsia.dev
DOMAIN-SUFFIX,g-tun.com
DOMAIN-SUFFIX,g.cn
DOMAIN-SUFFIX,g.co
DOMAIN-SUFFIX,g.dev
DOMAIN-SUFFIX,g.page
DOMAIN-SUFFIX,gateway.dev
DOMAIN-SUFFIX,gcr.io
DOMAIN-SUFFIX,gerritcodereview.com
DOMAIN-SUFFIX,getbumptop.com
DOMAIN-SUFFIX,ggoogle.com
DOMAIN-SUFFIX,gipscorp.com
DOMAIN-SUFFIX,gkecnapps.cn
DOMAIN-SUFFIX,globaledu.org
DOMAIN-SUFFIX,gmail.com
DOMAIN-SUFFIX,gmodules.com
DOMAIN-SUFFIX,gogle.com
DOMAIN-SUFFIX,gogole.com
DOMAIN-SUFFIX,gonglchuangl.net
DOMAIN-SUFFIX,goo.gl
DOMAIN-SUFFIX,googel.com
DOMAIN-SUFFIX,googil.com
DOMAIN-SUFFIX,googl.com
DOMAIN-SUFFIX,google-syndication.com
DOMAIN-SUFFIX,google.berlin
DOMAIN-SUFFIX,google.dev
DOMAIN-SUFFIX,google.net
DOMAIN-SUFFIX,google.org
DOMAIN-SUFFIX,google.ventures
DOMAIN-SUFFIX,googleacquisitionmigration.com
DOMAIN-SUFFIX,googleapis.cn
DOMAIN-SUFFIX,googleapis.com
DOMAIN-SUFFIX,googleapps.com
DOMAIN-SUFFIX,googlearth.com
DOMAIN-SUFFIX,googleblog.com
DOMAIN-SUFFIX,googlebot.com
DOMAIN-SUFFIX,googlecapital.com
DOMAIN-SUFFIX,googlecert.net
DOMAIN-SUFFIX,googlecnapps.cn
DOMAIN-SUFFIX,googlecode.com
DOMAIN-SUFFIX,googlecommerce.com
DOMAIN-SUFFIX,googlecompare.co.uk
DOMAIN-SUFFIX,googledanmark.com
DOMAIN-SUFFIX,googledomains.com
DOMAIN-SUFFIX,googledrive.com
DOMAIN-SUFFIX,googlee.com
DOMAIN-SUFFIX,googleearth.com
DOMAIN-SUFFIX,googlefiber.net
DOMAIN-SUFFIX,googlefinland.com
DOMAIN-SUFFIX,googlemail.com
DOMAIN-SUFFIX,googlemaps.com
DOMAIN-SUFFIX,googlepagecreator.com
DOMAIN-SUFFIX,googlephotos.com
DOMAIN-SUFFIX,googleplay.com
DOMAIN-SUFFIX,googleplus.com
DOMAIN-SUFFIX,googlesource.com
DOMAIN-SUFFIX,googlestore.com
DOMAIN-SUFFIX,googlesverige.com
DOMAIN-SUFFIX,googleusercontent.com
DOMAIN-SUFFIX,googleventures.com
DOMAIN-SUFFIX,googlr.com
DOMAIN-SUFFIX,goolge.com
DOMAIN-SUFFIX,gooogle.com
DOMAIN-SUFFIX,gridaware.app
DOMAIN-SUFFIX,gsrc.io
DOMAIN-SUFFIX,gstatic.cn
DOMAIN-SUFFIX,gstatic.com
DOMAIN-SUFFIX,gstaticcnapps.cn
DOMAIN-SUFFIX,gsuite.com
DOMAIN-SUFFIX,gv.com
DOMAIN-SUFFIX,gvt0.com
DOMAIN-SUFFIX,gvt1.com
DOMAIN-SUFFIX,gvt2.com
DOMAIN-SUFFIX,gvt3.com
DOMAIN-SUFFIX,gvt5.com
DOMAIN-SUFFIX,gvt6.com
DOMAIN-SUFFIX,gvt7.com
DOMAIN-SUFFIX,gvt9.com
DOMAIN-SUFFIX,hdrplusdata.org
DOMAIN-SUFFIX,hindiweb.com
DOMAIN-SUFFIX,howtogetmo.co.uk
DOMAIN-SUFFIX,html5rocks.com
DOMAIN-SUFFIX,hwgo.com
DOMAIN-SUFFIX,iamremarkable.org
DOMAIN-SUFFIX,igoogle.com
DOMAIN-SUFFIX,impermium.com
DOMAIN-SUFFIX,j2objc.org
DOMAIN-SUFFIX,jibemobile.com
DOMAIN-SUFFIX,keyhole.com
DOMAIN-SUFFIX,keytransparency.com
DOMAIN-SUFFIX,keytransparency.foo
DOMAIN-SUFFIX,keytransparency.org
DOMAIN-SUFFIX,lanternal.com
DOMAIN-SUFFIX,like.com
DOMAIN-SUFFIX,madewithcode.com
DOMAIN-SUFFIX,material.io
DOMAIN-SUFFIX,mdialog.com
DOMAIN-SUFFIX,meet.new
DOMAIN-SUFFIX,mfg-inspector.com
DOMAIN-SUFFIX,mobileview.page
DOMAIN-SUFFIX,moodstocks.com
DOMAIN-SUFFIX,near.by
DOMAIN-SUFFIX,nest.com
DOMAIN-SUFFIX,nomulus.foo
DOMAIN-SUFFIX,oauthz.com
DOMAIN-SUFFIX,on.here
DOMAIN-SUFFIX,on2.com
DOMAIN-SUFFIX,onefifteen.net
DOMAIN-SUFFIX,onefifteen.org
DOMAIN-SUFFIX,oneworldmanystories.com
DOMAIN-SUFFIX,openthread.io
DOMAIN-SUFFIX,openweave.io
DOMAIN-SUFFIX,orbitera.com
DOMAIN-SUFFIX,page.link
DOMAIN-SUFFIX,pagespeedmobilizer.com
DOMAIN-SUFFIX,pageview.mobi
DOMAIN-SUFFIX,panoramio.com
DOMAIN-SUFFIX,partylikeits1986.org
DOMAIN-SUFFIX,paxlicense.org
DOMAIN-SUFFIX,picasa.com
DOMAIN-SUFFIX,picasaweb.com
DOMAIN-SUFFIX,picasaweb.net
DOMAIN-SUFFIX,picasaweb.org
DOMAIN-SUFFIX,picnik.com
DOMAIN-SUFFIX,pittpatt.com
DOMAIN-SUFFIX,pixate.com
DOMAIN-SUFFIX,postini.com
DOMAIN-SUFFIX,privacysandbox.com
DOMAIN-SUFFIX,projectara.com
DOMAIN-SUFFIX,projectbaseline.com
DOMAIN-SUFFIX,publishproxy.com
DOMAIN-SUFFIX,questvisual.com
DOMAIN-SUFFIX,quickoffice.com
DOMAIN-SUFFIX,quiksee.com
DOMAIN-SUFFIX,revolv.com
DOMAIN-SUFFIX,ridepenguin.com
DOMAIN-SUFFIX,run.app
DOMAIN-SUFFIX,savethedate.foo
DOMAIN-SUFFIX,saynow.com
DOMAIN-SUFFIX,schemer.com
DOMAIN-SUFFIX,screenwisetrends.com
DOMAIN-SUFFIX,screenwisetrendspanel.com
DOMAIN-SUFFIX,snapseed.com
DOMAIN-SUFFIX,solveforx.com
DOMAIN-SUFFIX,stadia.dev
DOMAIN-SUFFIX,stcroixmosquito.com
DOMAIN-SUFFIX,stcroixmosquitoproject.com
DOMAIN-SUFFIX,studywatchbyverily.com
DOMAIN-SUFFIX,studywatchbyverily.org
DOMAIN-SUFFIX,stxmosquito.com
DOMAIN-SUFFIX,stxmosquitoproject.com
DOMAIN-SUFFIX,stxmosquitoproject.net
DOMAIN-SUFFIX,stxmosquitoproject.org
DOMAIN-SUFFIX,synergyse.com
DOMAIN-SUFFIX,tensorflow.org
DOMAIN-SUFFIX,tfhub.dev
DOMAIN-SUFFIX,thecleversense.com
DOMAIN-SUFFIX,thegooglestore.com
DOMAIN-SUFFIX,thinkquarterly.co.uk
DOMAIN-SUFFIX,thinkquarterly.com
DOMAIN-SUFFIX,thinkwithgoogle.com
DOMAIN-SUFFIX,tiltbrush.com
DOMAIN-SUFFIX,txcloud.net
DOMAIN-SUFFIX,txvia.com
DOMAIN-SUFFIX,unfiltered.news
DOMAIN-SUFFIX,useplannr.com
DOMAIN-SUFFIX,usvimosquito.com
DOMAIN-SUFFIX,usvimosquitoproject.com
DOMAIN-SUFFIX,velostrata.com
DOMAIN-SUFFIX,verily.com
DOMAIN-SUFFIX,verilylifesciences.com
DOMAIN-SUFFIX,verilystudyhub.com
DOMAIN-SUFFIX,verilystudywatch.com
DOMAIN-SUFFIX,verilystudywatch.org
DOMAIN-SUFFIX,wallet.com
DOMAIN-SUFFIX,waymo.com
DOMAIN-SUFFIX,waze.com
DOMAIN-SUFFIX,web.app
DOMAIN-SUFFIX,web.dev
DOMAIN-SUFFIX,webappfieldguide.com
DOMAIN-SUFFIX,webmproject.org
DOMAIN-SUFFIX,webpkgcache.com
DOMAIN-SUFFIX,webrtc.org
DOMAIN-SUFFIX,weltweitwachsen.de
DOMAIN-SUFFIX,whatbrowser.org
DOMAIN-SUFFIX,widevine.com
DOMAIN-SUFFIX,withgoogle.com
DOMAIN-SUFFIX,womenwill.com
DOMAIN-SUFFIX,womenwill.com.br
DOMAIN-SUFFIX,womenwill.id
DOMAIN-SUFFIX,womenwill.in
DOMAIN-SUFFIX,womenwill.mx
DOMAIN-SUFFIX,x.company
DOMAIN-SUFFIX,x.team
DOMAIN-SUFFIX,xn--9kr7l.com
DOMAIN-SUFFIX,xn--9trs65b.com
DOMAIN-SUFFIX,xn--flw351e.com
DOMAIN-SUFFIX,xn--ggle-55da.com
DOMAIN-SUFFIX,xn--gogl-0nd52e.com
DOMAIN-SUFFIX,xn--gogl-1nd42e.com
DOMAIN-SUFFIX,xn--ngstr-lra8j.com
DOMAIN-SUFFIX,xplr.co
DOMAIN-SUFFIX,zukunftswerkstatt.de

# > Instagram
DOMAIN-SUFFIX,achat-followers-instagram.com
DOMAIN-SUFFIX,acheter-followers-instagram.com
DOMAIN-SUFFIX,acheterdesfollowersinstagram.com
DOMAIN-SUFFIX,acheterfollowersinstagram.com
DOMAIN-SUFFIX,bookstagram.com
DOMAIN-SUFFIX,carstagram.com
DOMAIN-SUFFIX,cdninstagram.com
DOMAIN-SUFFIX,chickstagram.com
DOMAIN-SUFFIX,ig.me
DOMAIN-SUFFIX,igcdn.com
DOMAIN-SUFFIX,igsonar.com
DOMAIN-SUFFIX,igtv.com
DOMAIN-SUFFIX,imstagram.com
DOMAIN-SUFFIX,imtagram.com
DOMAIN-SUFFIX,instaadder.com
DOMAIN-SUFFIX,instachecker.com
DOMAIN-SUFFIX,instafallow.com
DOMAIN-SUFFIX,instafollower.com
DOMAIN-SUFFIX,instagainer.com
DOMAIN-SUFFIX,instagda.com
DOMAIN-SUFFIX,instagify.com
DOMAIN-SUFFIX,instagmania.com
DOMAIN-SUFFIX,instagor.com
DOMAIN-SUFFIX,instagram-brand.com
DOMAIN-SUFFIX,instagram-engineering.com
DOMAIN-SUFFIX,instagram-help.com
DOMAIN-SUFFIX,instagram-press.com
DOMAIN-SUFFIX,instagram-press.net
DOMAIN-SUFFIX,instagram.com
DOMAIN-SUFFIX,instagramci.com
DOMAIN-SUFFIX,instagramcn.com
DOMAIN-SUFFIX,instagramdi.com
DOMAIN-SUFFIX,instagramhashtags.net
DOMAIN-SUFFIX,instagramhilecim.com
DOMAIN-SUFFIX,instagramhilesi.org
DOMAIN-SUFFIX,instagramium.com
DOMAIN-SUFFIX,instagramizlenme.com
DOMAIN-SUFFIX,instagramkusu.com
DOMAIN-SUFFIX,instagramlogin.com
DOMAIN-SUFFIX,instagramm.com
DOMAIN-SUFFIX,instagramn.com
DOMAIN-SUFFIX,instagrampartners.com
DOMAIN-SUFFIX,instagramphoto.com
DOMAIN-SUFFIX,instagramq.com
DOMAIN-SUFFIX,instagramsepeti.com
DOMAIN-SUFFIX,instagramtakipcisatinal.net
DOMAIN-SUFFIX,instagramtakiphilesi.com
DOMAIN-SUFFIX,instagramtips.com
DOMAIN-SUFFIX,instagramtr.com
DOMAIN-SUFFIX,instagran.com
DOMAIN-SUFFIX,instagranm.com
DOMAIN-SUFFIX,instagrem.com
DOMAIN-SUFFIX,instagrm.com
DOMAIN-SUFFIX,instagtram.com
DOMAIN-SUFFIX,instagy.com
DOMAIN-SUFFIX,instamgram.com
DOMAIN-SUFFIX,instangram.com
DOMAIN-SUFFIX,instanttelegram.com
DOMAIN-SUFFIX,instaplayer.net
DOMAIN-SUFFIX,instastyle.tv
DOMAIN-SUFFIX,instgram.com
DOMAIN-SUFFIX,intagram.com
DOMAIN-SUFFIX,intagrm.com
DOMAIN-SUFFIX,intgram.com
DOMAIN-SUFFIX,kingstagram.com
DOMAIN-SUFFIX,lnstagram-help.com
DOMAIN-SUFFIX,theinstagramhack.com
DOMAIN-SUFFIX,oninstagram.com
DOMAIN-SUFFIX,online-instagram.com
DOMAIN-SUFFIX,onlineinstagram.com
DOMAIN-SUFFIX,web-instagram.net
DOMAIN-SUFFIX,wwwinstagram.com

# > Facebook
DOMAIN-SUFFIX,fb.me
DOMAIN-SUFFIX,fbcdn.net

# > Amazon
DOMAIN-SUFFIX,amazon
DOMAIN-SUFFIX,xn--cckwcxetd
DOMAIN-SUFFIX,xn--jlq480n2rg
DOMAIN-SUFFIX,yamaxun
DOMAIN-SUFFIX,zappos
DOMAIN-SUFFIX,a2z.com
DOMAIN-SUFFIX,aboutamazon.com
DOMAIN-SUFFIX,amaaozn.com
DOMAIN-SUFFIX,amazon-fashions.com
DOMAIN-SUFFIX,amazon-jp-recruiting.com
DOMAIN-SUFFIX,amazon-lantern.com
DOMAIN-SUFFIX,amazon-launchpad.com
DOMAIN-SUFFIX,amazon.sg
DOMAIN-SUFFIX,amazonalexavoxcon.com
DOMAIN-SUFFIX,amazonauthorinsights.com
DOMAIN-SUFFIX,amazonbusiness.org
DOMAIN-SUFFIX,amazonbusinessblog.com
DOMAIN-SUFFIX,amazondevicesupport.com
DOMAIN-SUFFIX,amazonfctours.com
DOMAIN-SUFFIX,amazonianblog.com
DOMAIN-SUFFIX,amazonimages.com
DOMAIN-SUFFIX,amazonlaunchpad.com
DOMAIN-SUFFIX,amazonliterarypartnership.com
DOMAIN-SUFFIX,amazonlumberyard.wang
DOMAIN-SUFFIX,amazonpay.com
DOMAIN-SUFFIX,amazonsdi.com
DOMAIN-SUFFIX,amazonstudiosguilds.com
DOMAIN-SUFFIX,amazonvideodirect.com
DOMAIN-SUFFIX,amzn.asia
DOMAIN-SUFFIX,amzn.com
DOMAIN-SUFFIX,amzn.to
DOMAIN-SUFFIX,amznl.com
DOMAIN-SUFFIX,associates-amazon.com
DOMAIN-SUFFIX,gameon-masters.com
DOMAIN-SUFFIX,gdansk-amazon.com
DOMAIN-SUFFIX,images-amazon.com
DOMAIN-SUFFIX,media-amazon.com
DOMAIN-SUFFIX,primeday.info
DOMAIN-SUFFIX,siege-amazon.com
DOMAIN-SUFFIX,ssl-images-amazon.com
DOMAIN-SUFFIX,ueberamazon.de
DOMAIN-SUFFIX,yamaxun.com
DOMAIN-SUFFIX,alexa.com
DOMAIN-SUFFIX,audible.com
DOMAIN-SUFFIX,createspace.com

# > Cloudflare
DOMAIN-SUFFIX,cloudflare-dns.com
DOMAIN-SUFFIX,cloudflare-ipfs.com
DOMAIN-SUFFIX,cloudflare-quic.com
DOMAIN-SUFFIX,cloudflare.com
DOMAIN-SUFFIX,cloudflare.net
DOMAIN-SUFFIX,cloudflareapps.com
DOMAIN-SUFFIX,cloudflarebolt.com
DOMAIN-SUFFIX,cloudflareclient.com
DOMAIN-SUFFIX,cloudflareinsights.com
DOMAIN-SUFFIX,cloudflareok.com
DOMAIN-SUFFIX,cloudflareresolve.com
DOMAIN-SUFFIX,cloudflaressl.com
DOMAIN-SUFFIX,cloudflarestatus.com
DOMAIN-SUFFIX,cloudflarestream.com
DOMAIN-SUFFIX,cloudflaretest.com
DOMAIN-SUFFIX,cloudflarewarp.com
DOMAIN-SUFFIX,one.one.one
DOMAIN-SUFFIX,pacloudflare.com
DOMAIN-SUFFIX,pages.dev
DOMAIN-SUFFIX,trycloudflare.com
DOMAIN-SUFFIX,videodelivery.net
DOMAIN-SUFFIX,warp.plus
DOMAIN-SUFFIX,workers.dev

# > Akamai
DOMAIN-SUFFIX,ak1.net
DOMAIN-SUFFIX,aka-ai.com
DOMAIN-SUFFIX,aka-ai.net
DOMAIN-SUFFIX,akacrypto.net
DOMAIN-SUFFIX,akadeem.net
DOMAIN-SUFFIX,akadns.com
DOMAIN-SUFFIX,akadns6.net
DOMAIN-SUFFIX,akaeai.com
DOMAIN-SUFFIX,akafms.net
DOMAIN-SUFFIX,akahost.net
DOMAIN-SUFFIX,akaint.net
DOMAIN-SUFFIX,akam.net
DOMAIN-SUFFIX,akamaa.com
DOMAIN-SUFFIX,akamah.com
DOMAIN-SUFFIX,akamak.com
DOMAIN-SUFFIX,akamam.com
DOMAIN-SUFFIX,akamai-access.com
DOMAIN-SUFFIX,akamai-access.net
DOMAIN-SUFFIX,akamai-cdn.com
DOMAIN-SUFFIX,akamai-platform-internal.net
DOMAIN-SUFFIX,akamai-platform-staging.com
DOMAIN-SUFFIX,akamai-platform.net
DOMAIN-SUFFIX,akamai-regression.net
DOMAIN-SUFFIX,akamai-staging.net
DOMAIN-SUFFIX,akamai-sucks.net
DOMAIN-SUFFIX,akamai-thailand.com
DOMAIN-SUFFIX,akamai-thailand.net
DOMAIN-SUFFIX,akamai-trials.com
DOMAIN-SUFFIX,akamai.co.kr
DOMAIN-SUFFIX,akamai.com
DOMAIN-SUFFIX,akamai.net
DOMAIN-SUFFIX,akamaientrypoint.net
DOMAIN-SUFFIX,akamaietpcnctest.com
DOMAIN-SUFFIX,akamaietpcompromisedcnctest.com
DOMAIN-SUFFIX,akamaietpcompromisedmalwaretest.com
DOMAIN-SUFFIX,akamaietpmalwaretest.com
DOMAIN-SUFFIX,akamaietpphishingtest.com
DOMAIN-SUFFIX,akamaihd-staging.net
DOMAIN-SUFFIX,akamaihd.com
DOMAIN-SUFFIX,akamaihd.net
DOMAIN-SUFFIX,akamaimagicmath.net
DOMAIN-SUFFIX,akamainewzealand.com
DOMAIN-SUFFIX,akamaiphillipines.com
DOMAIN-SUFFIX,akamaiphillipines.net
DOMAIN-SUFFIX,akamaitech.com
DOMAIN-SUFFIX,akamaitech.net
DOMAIN-SUFFIX,akamaitechnologies.com
DOMAIN-SUFFIX,akamaitechnologies.net
DOMAIN-SUFFIX,akamaisingapore.net
DOMAIN-SUFFIX,akamaized-staging.net
DOMAIN-SUFFIX,akamaized.net
DOMAIN-SUFFIX,akamaizercentral.com
DOMAIN-SUFFIX,akamci.com
DOMAIN-SUFFIX,akami.com
DOMAIN-SUFFIX,akami.net
DOMAIN-SUFFIX,akamii.com
DOMAIN-SUFFIX,akamqi.com
DOMAIN-SUFFIX,akastream.com
DOMAIN-SUFFIX,akastream.net
DOMAIN-SUFFIX,akatns.net
DOMAIN-SUFFIX,iamakamai.com
DOMAIN-SUFFIX,iamakamai.net
DOMAIN-SUFFIX,soasta-dswb.com
DOMAIN-SUFFIX,srtcdn.net

# > Fastly
DOMAIN-SUFFIX,fastly.com
DOMAIN-SUFFIX,fastly.net
DOMAIN-SUFFIX,fastlylabs.com
DOMAIN-SUFFIX,fastlylb.net
DOMAIN-SUFFIX,fastly-terrarium.com
DOMAIN-SUFFIX,zencdn.net

# > Fastly
DOMAIN-SUFFIX,stackpath.com
DOMAIN-SUFFIX,stackpath.dev

# > AWS
DOMAIN-SUFFIX,aws
DOMAIN-SUFFIX,acmvalidations.com
DOMAIN-SUFFIX,acmvalidationsaws.com
DOMAIN-SUFFIX,aesworkshops.com
DOMAIN-SUFFIX,amazonaws-china.com
DOMAIN-SUFFIX,amazonaws.co.uk
DOMAIN-SUFFIX,amazonaws.com
DOMAIN-SUFFIX,amazonaws.tv
DOMAIN-SUFFIX,amazonworkdocs.com
DOMAIN-SUFFIX,amplifyapp.com
DOMAIN-SUFFIX,amplifyframework.com
DOMAIN-SUFFIX,aws-iot-hackathon.com
DOMAIN-SUFFIX,awsautopilot.com
DOMAIN-SUFFIX,awsautoscaling.com
DOMAIN-SUFFIX,awsbraket.com
DOMAIN-SUFFIX,awscommandlineinterface.com
DOMAIN-SUFFIX,awsedstart.com
DOMAIN-SUFFIX,awseducate.com
DOMAIN-SUFFIX,awseducate.net
DOMAIN-SUFFIX,awseducate.org
DOMAIN-SUFFIX,awsloft-johannesburg.com
DOMAIN-SUFFIX,awsloft-stockholm.com
DOMAIN-SUFFIX,awssecworkshops.com
DOMAIN-SUFFIX,awsstatic.com
DOMAIN-SUFFIX,awsthinkbox.com
DOMAIN-SUFFIX,cdkworkshop.com
DOMAIN-SUFFIX,cloudfront.net
DOMAIN-SUFFIX,containersonaws.com
DOMAIN-SUFFIX,elasticbeanstalk.com
DOMAIN-SUFFIX,thinkboxsoftware.com
  
# > PayPal
DOMAIN-KEYWORD,paypal
DOMAIN-SUFFIX,paypal.com
DOMAIN-SUFFIX,paypalobjects.com

# > Netflix
DOMAIN-SUFFIX,fast.com
DOMAIN-SUFFIX,netflix.ca
DOMAIN-SUFFIX,netflix.com
DOMAIN-SUFFIX,netflix.net
DOMAIN-SUFFIX,netflixinvestor.com
DOMAIN-SUFFIX,netflixtechblog.com
DOMAIN-SUFFIX,nflxext.com
DOMAIN-SUFFIX,nflximg.com
DOMAIN-SUFFIX,nflximg.net
DOMAIN-SUFFIX,nflxsearch.net
DOMAIN-SUFFIX,nflxso.net
DOMAIN-SUFFIX,nflxvideo.net

DOMAIN-SUFFIX,netflixdnstest1.com
DOMAIN-SUFFIX,netflixdnstest2.com
DOMAIN-SUFFIX,netflixdnstest3.com
DOMAIN-SUFFIX,netflixdnstest4.com
DOMAIN-SUFFIX,netflixdnstest5.com
DOMAIN-SUFFIX,netflixdnstest6.com
DOMAIN-SUFFIX,netflixdnstest7.com
DOMAIN-SUFFIX,netflixdnstest8.com
DOMAIN-SUFFIX,netflixdnstest9.com
DOMAIN-SUFFIX,netflixdnstest10.com

DOMAIN-SUFFIX,amazonaws.com
DOMAIN-SUFFIX,akamaiedge.net

DOMAIN,netflix.com.edgesuite.net
  
DOMAIN-KEYWORD,netflixdnstest
DOMAIN-KEYWORD,dualstack.apiproxy-
DOMAIN-KEYWORD,dualstack.ichnaea-web-
DOMAIN-KEYWORD,apiproxy-device-prod-nlb-

IP-CIDR,23.246.0.0/18,no-resolve
IP-CIDR,37.77.184.0/21,no-resolve
IP-CIDR,38.72.126.0/24,no-resolve
IP-CIDR,45.57.0.0/17,no-resolve
IP-CIDR,64.120.128.0/17,no-resolve
IP-CIDR,66.197.128.0/17,no-resolve
IP-CIDR,69.53.224.0/19,no-resolve
IP-CIDR,103.87.204.0/22,no-resolve
IP-CIDR,108.175.32.0/20,no-resolve
IP-CIDR,185.2.220.0/22,no-resolve
IP-CIDR,185.9.188.0/22,no-resolve
IP-CIDR,192.173.64.0/18,no-resolve
IP-CIDR,198.38.96.0/19,no-resolve
IP-CIDR,198.45.48.0/20,no-resolve
IP-CIDR,208.75.76.0/22,no-resolve
IP-CIDR,34.210.42.111/32,no-resolve
IP-CIDR,52.89.124.203/32,no-resolve
IP-CIDR,54.148.37.5/32,no-resolve

IP-CIDR,8.8.8.8/32,no-resolve
IP-CIDR,8.8.4.4/32,no-resolve

# > Disney Plus
DOMAIN-SUFFIX,abc-studios.com
DOMAIN-SUFFIX,abc.com
DOMAIN-SUFFIX,edgedatg.com

DOMAIN-SUFFIX,bamgrid.com
DOMAIN-SUFFIX,dmed.technology

DOMAIN-SUFFIX,dtci.co
DOMAIN-SUFFIX,dtci.technology
DOMAIN-SUFFIX,espn.co.uk
DOMAIN-SUFFIX,espn.com
DOMAIN-SUFFIX,espn.net
DOMAIN-SUFFIX,espncdn.com
DOMAIN-SUFFIX,espnqa.com
DOMAIN-SUFFIX,watchespn.com
DOMAIN-SUFFIX,omtrdc.net

DOMAIN-SUFFIX,marvel.com
DOMAIN-SUFFIX,marvel10thanniversary.com
DOMAIN-SUFFIX,marveldimensionofheroes.com
DOMAIN-SUFFIX,marvelparty.net
DOMAIN-SUFFIX,marvelpinball.com
DOMAIN-SUFFIX,marvelsdoubleagent.com
DOMAIN-SUFFIX,marvelspotlightplays.com
DOMAIN-SUFFIX,marvelsuperheroseptember.com
DOMAIN-SUFFIX,marvelsuperwar.com
DOMAIN-SUFFIX,themarvelexperiencetour.com

DOMAIN-SUFFIX,natgeomaps.com
DOMAIN-SUFFIX,nationalgeographic.com
DOMAIN-SUFFIX,nationalgeographicpartners.com
DOMAIN-SUFFIX,ngeo.com

DOMAIN-SUFFIX,disney.asia
DOMAIN-SUFFIX,disney.co.jp
DOMAIN-SUFFIX,disney.co.kr
DOMAIN-SUFFIX,disney.com
DOMAIN-SUFFIX,disney.sg
DOMAIN-SUFFIX,20thcenturystudios.com.au
DOMAIN-SUFFIX,20thcenturystudios.com.br
DOMAIN-SUFFIX,20thcenturystudios.jp
DOMAIN-SUFFIX,adventuresbydisney.com
DOMAIN-SUFFIX,babble.com
DOMAIN-SUFFIX,babyzone.com
DOMAIN-SUFFIX,bamgrid.com
DOMAIN-SUFFIX,beautyandthebeastmusical.co.uk
DOMAIN-SUFFIX,dilcdn.com
DOMAIN-SUFFIX,disney-asia.com
DOMAIN-SUFFIX,disney-discount.com
DOMAIN-SUFFIX,disney-plus.net
DOMAIN-SUFFIX,disney-portal.my.onetrust.com
DOMAIN-SUFFIX,disney-studio.com
DOMAIN-SUFFIX,disney-studio.net
DOMAIN-SUFFIX,disney.my.sentry.io
DOMAIN-SUFFIX,disneyadsales.com
DOMAIN-SUFFIX,disneyarena.com
DOMAIN-SUFFIX,disneyaulani.com
DOMAIN-SUFFIX,disneybaby.com
DOMAIN-SUFFIX,disneycareers.com
DOMAIN-SUFFIX,disneychannelonstage.com
DOMAIN-SUFFIX,disneychannelroadtrip.com
DOMAIN-SUFFIX,disneycruisebrasil.com
DOMAIN-SUFFIX,disneyenconcert.com
DOMAIN-SUFFIX,disneyiejobs.com
DOMAIN-SUFFIX,disneyinflight.com
DOMAIN-SUFFIX,disneyinternational.com
DOMAIN-SUFFIX,disneyinternationalhd.com
DOMAIN-SUFFIX,disneyjunior.com
DOMAIN-SUFFIX,disneyjuniortreataday.com
DOMAIN-SUFFIX,disneylatino.com
DOMAIN-SUFFIX,disneymagicmomentsme.com
DOMAIN-SUFFIX,disneyme.com
DOMAIN-SUFFIX,disneymeetingsandevents.com
DOMAIN-SUFFIX,disneymovieinsiders.com
DOMAIN-SUFFIX,disneymusicpromotion.com
DOMAIN-SUFFIX,disneynewseries.com
DOMAIN-SUFFIX,disneynow.com
DOMAIN-SUFFIX,disneypeoplesurveys.com
DOMAIN-SUFFIX,disneyplus.bn5x.net
DOMAIN-SUFFIX,disneyplus.com
DOMAIN-SUFFIX,disneyplus.com.ssl.sc.omtrdc.net
DOMAIN-SUFFIX,disneyredirects.com
DOMAIN-SUFFIX,disneysrivieraresort.com
DOMAIN-SUFFIX,disneystore.com
DOMAIN-SUFFIX,disneystreaming.com
DOMAIN-SUFFIX,disneysubscription.com
DOMAIN-SUFFIX,disneytickets.co.uk
DOMAIN-SUFFIX,disneyturkiye.com.tr
DOMAIN-SUFFIX,disneytvajobs.com
DOMAIN-SUFFIX,disneyworld-go.com
DOMAIN-SUFFIX,dssott.com
DOMAIN-SUFFIX,go-disneyworldgo.com
DOMAIN-SUFFIX,go.com
DOMAIN-SUFFIX,mickey.tv
DOMAIN-SUFFIX,moviesanywhere.com
DOMAIN-SUFFIX,nomadlandmovie.ch
DOMAIN-SUFFIX,playmation.com
DOMAIN-SUFFIX,shopdisney.com
DOMAIN-SUFFIX,shops-disney.com
DOMAIN-SUFFIX,sorcerersarena.com
DOMAIN-SUFFIX,spaindisney.com
DOMAIN-SUFFIX,star-brasil.com
DOMAIN-SUFFIX,star-latam.com
DOMAIN-SUFFIX,starwars.com
DOMAIN-SUFFIX,starwarsgalacticstarcruiser.com
DOMAIN-SUFFIX,starwarskids.com
DOMAIN-SUFFIX,streamingdisney.net
DOMAIN-SUFFIX,thestationbymaker.com
DOMAIN-SUFFIX,thisispolaris.com
DOMAIN-SUFFIX,watchdisneyfe.com

# > Other
DOMAIN-KEYWORD,appledaily
DOMAIN-KEYWORD,beetalk
DOMAIN-KEYWORD,blogspot
DOMAIN-KEYWORD,dropbox
DOMAIN-KEYWORD,facebook
DOMAIN-KEYWORD,github
DOMAIN-KEYWORD,instagram
DOMAIN-KEYWORD,twitter
DOMAIN-KEYWORD,whatsapp
DOMAIN-KEYWORD,google
