# > CUS
DOMAIN-SUFFIX,owlook.com.cn
DOMAIN-SUFFIX,6kshu.com
DOMAIN-SUFFIX,hostloc.com
DOMAIN-SUFFIX,v2ex.com
DOMAIN-SUFFIX,deepl.com
DOMAIN-SUFFIX,ampproject.org
DOMAIN,token.safebrowsing.apple
DOMAIN-SUFFIX,vhx.tv
DOMAIN-SUFFIX,vhx.com
DOMAIN-SUFFIX,gitcdn.xyz
DOMAIN-SUFFIX,gitcdn.link
DOMAIN-SUFFIX,secureservercdn.net
DOMAIN-SUFFIX,privnote.com
DOMAIN-SUFFIX,lvv2.com
DOMAIN-SUFFIX,good.news
DOMAIN-SUFFIX,openai.com
DOMAIN-SUFFIX,vn

# > Apple
DOMAIN-SUFFIX,cdn-apple.com
DOMAIN-SUFFIX,mzstatic.com
DOMAIN-SUFFIX,aaplimg.com
DOMAIN-SUFFIX,apple.co
DOMAIN-SUFFIX,apple.com
DOMAIN-SUFFIX,icloud-content.com
DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,itunes.com
DOMAIN-SUFFIX,itunes.apple.com
DOMAIN-SUFFIX,lookup-api.apple.com
DOMAIN-SUFFIX,me.com

# > Twitter
DOMAIN-SUFFIX,ads-twitter.com
DOMAIN-SUFFIX,cms-twdigitalassets.com
DOMAIN-SUFFIX,periscope.tv
DOMAIN-SUFFIX,pscp.tv
DOMAIN-SUFFIX,t.co
DOMAIN-SUFFIX,tellapart.com
DOMAIN-SUFFIX,tweetdeck.com
DOMAIN-SUFFIX,twimg.com
DOMAIN-SUFFIX,twitpic.com
DOMAIN-SUFFIX,twitter.com
DOMAIN-SUFFIX,twitter.jp
DOMAIN-SUFFIX,twittercommunity.com
DOMAIN-SUFFIX,twitterflightschool.com
DOMAIN-SUFFIX,twitterinc.com
DOMAIN-SUFFIX,twitteroauth.com
DOMAIN-SUFFIX,twitterstat.us
DOMAIN-SUFFIX,twtrdns.net
DOMAIN-SUFFIX,twttr.com
DOMAIN-SUFFIX,vine.co

# > Linkedin
DOMAIN-SUFFIX,bizographics.com
DOMAIN-SUFFIX,l-0005.dc-msedge.net
DOMAIN-SUFFIX,l-0005.l-msedge.net
DOMAIN-SUFFIX,licdn.com
DOMAIN-SUFFIX,linkedin.at
DOMAIN-SUFFIX,linkedin.com
DOMAIN-SUFFIX,lnkd.in
DOMAIN,e122475.dscg.akamaiedge.net
DOMAIN,licdn.cn.cdn20.com
DOMAIN,linkedin.sc.omtrdc.net

# > TikTok
DOMAIN-SUFFIX,byteoversea.com
DOMAIN-SUFFIX,muscdn.com
DOMAIN-SUFFIX,musical.ly
DOMAIN-SUFFIX,tik-tokapi.com
DOMAIN-SUFFIX,tiktok.com
DOMAIN-SUFFIX,tiktokcdn.com
DOMAIN-SUFFIX,tiktokv.com
DOMAIN,p16-tiktokcdn-com.akamaized.net

# > Line
DOMAIN-SUFFIX,gcld-line.com
DOMAIN-SUFFIX,lin.ee
DOMAIN-SUFFIX,line-apps-beta.com
DOMAIN-SUFFIX,line-apps-rc.com
DOMAIN-SUFFIX,line-apps.com
DOMAIN-SUFFIX,line-beta.me
DOMAIN-SUFFIX,line-cdn.net
DOMAIN-SUFFIX,line-scdn.net
DOMAIN-SUFFIX,line.me
DOMAIN-SUFFIX,line.naver.jp
DOMAIN-SUFFIX,linecorp.com
DOMAIN-SUFFIX,linefriends.com
DOMAIN-SUFFIX,linefriends.com.tw
DOMAIN-SUFFIX,linegame.jp
DOMAIN-SUFFIX,linemobile.com
DOMAIN-SUFFIX,linemyshop.com
DOMAIN-SUFFIX,lineshoppingseller.com
DOMAIN-SUFFIX,linetv.tw
DOMAIN-SUFFIX,nhncorp.jp

# > Meta
DOMAIN-SUFFIX,meta.com

# > WhatsApp
DOMAIN-SUFFIX,wa.me
DOMAIN-SUFFIX,whatsapp-plus.info
DOMAIN-SUFFIX,whatsapp-plus.me
DOMAIN-SUFFIX,whatsapp-plus.net
DOMAIN-SUFFIX,whatsapp.cc
DOMAIN-SUFFIX,whatsapp.com
DOMAIN-SUFFIX,whatsapp.info
DOMAIN-SUFFIX,whatsapp.net
DOMAIN-SUFFIX,whatsapp.org
DOMAIN-SUFFIX,whatsapp.tv
DOMAIN-SUFFIX,whatsappbrand.com

# > Facebook Messenger
DOMAIN-SUFFIX,fbmessenger.com
DOMAIN-SUFFIX,m.me
DOMAIN-SUFFIX,messenger.com
DOMAIN-SUFFIX,nbabot.net

# > Instagram
DOMAIN-SUFFIX,achat-followers-instagram.com
DOMAIN-SUFFIX,acheter-followers-instagram.com
DOMAIN-SUFFIX,acheterdesfollowersinstagram.com
DOMAIN-SUFFIX,acheterfollowersinstagram.com
DOMAIN-SUFFIX,bookstagram.com
DOMAIN-SUFFIX,carstagram.com
DOMAIN-SUFFIX,cdninstagram.com
DOMAIN-SUFFIX,chickstagram.com
DOMAIN-SUFFIX,ig.me
DOMAIN-SUFFIX,igcdn.com
DOMAIN-SUFFIX,igsonar.com
DOMAIN-SUFFIX,igtv.com
DOMAIN-SUFFIX,imstagram.com
DOMAIN-SUFFIX,imtagram.com
DOMAIN-SUFFIX,instaadder.com
DOMAIN-SUFFIX,instachecker.com
DOMAIN-SUFFIX,instafallow.com
DOMAIN-SUFFIX,instafollower.com
DOMAIN-SUFFIX,instagainer.com
DOMAIN-SUFFIX,instagda.com
DOMAIN-SUFFIX,instagify.com
DOMAIN-SUFFIX,instagmania.com
DOMAIN-SUFFIX,instagor.com
DOMAIN-SUFFIX,instagram-brand.com
DOMAIN-SUFFIX,instagram-engineering.com
DOMAIN-SUFFIX,instagram-help.com
DOMAIN-SUFFIX,instagram-press.com
DOMAIN-SUFFIX,instagram-press.net
DOMAIN-SUFFIX,instagram.com
DOMAIN-SUFFIX,instagramci.com
DOMAIN-SUFFIX,instagramcn.com
DOMAIN-SUFFIX,instagramdi.com
DOMAIN-SUFFIX,instagramhashtags.net
DOMAIN-SUFFIX,instagramhilecim.com
DOMAIN-SUFFIX,instagramhilesi.org
DOMAIN-SUFFIX,instagramium.com
DOMAIN-SUFFIX,instagramizlenme.com
DOMAIN-SUFFIX,instagramkusu.com
DOMAIN-SUFFIX,instagramlogin.com
DOMAIN-SUFFIX,instagramm.com
DOMAIN-SUFFIX,instagramn.com
DOMAIN-SUFFIX,instagrampartners.com
DOMAIN-SUFFIX,instagramphoto.com
DOMAIN-SUFFIX,instagramq.com
DOMAIN-SUFFIX,instagramsepeti.com
DOMAIN-SUFFIX,instagramtakipcisatinal.net
DOMAIN-SUFFIX,instagramtakiphilesi.com
DOMAIN-SUFFIX,instagramtips.com
DOMAIN-SUFFIX,instagramtr.com
DOMAIN-SUFFIX,instagran.com
DOMAIN-SUFFIX,instagranm.com
DOMAIN-SUFFIX,instagrem.com
DOMAIN-SUFFIX,instagrm.com
DOMAIN-SUFFIX,instagtram.com
DOMAIN-SUFFIX,instagy.com
DOMAIN-SUFFIX,instamgram.com
DOMAIN-SUFFIX,instangram.com
DOMAIN-SUFFIX,instanttelegram.com
DOMAIN-SUFFIX,instaplayer.net
DOMAIN-SUFFIX,instastyle.tv
DOMAIN-SUFFIX,instgram.com
DOMAIN-SUFFIX,intagram.com
DOMAIN-SUFFIX,intagrm.com
DOMAIN-SUFFIX,intgram.com
DOMAIN-SUFFIX,kingstagram.com
DOMAIN-SUFFIX,lnstagram-help.com
DOMAIN-SUFFIX,theinstagramhack.com
DOMAIN-SUFFIX,oninstagram.com
DOMAIN-SUFFIX,online-instagram.com
DOMAIN-SUFFIX,onlineinstagram.com
DOMAIN-SUFFIX,web-instagram.net
DOMAIN-SUFFIX,wwwinstagram.com

# > Facebook
DOMAIN-SUFFIX,aboutfacebook.com
DOMAIN-SUFFIX,accessfacebookfromschool.com
DOMAIN-SUFFIX,acebooik.com
DOMAIN-SUFFIX,acebook.com
DOMAIN-SUFFIX,advancediddetection.com
DOMAIN-SUFFIX,askfacebook.net
DOMAIN-SUFFIX,askfacebook.org
DOMAIN-SUFFIX,atdmt2.com
DOMAIN-SUFFIX,atlasdmt.com
DOMAIN-SUFFIX,atlasonepoint.com
DOMAIN-SUFFIX,buyingfacebooklikes.com
DOMAIN-SUFFIX,careersatfb.com
DOMAIN-SUFFIX,celebgramme.com
DOMAIN-SUFFIX,china-facebook.com
DOMAIN-SUFFIX,click-url.com
DOMAIN-SUFFIX,como-hackearfacebook.com
DOMAIN-SUFFIX,crowdtangle.com
DOMAIN-SUFFIX,dacebook.com
DOMAIN-SUFFIX,dlfacebook.com
DOMAIN-SUFFIX,dotfacebook.com
DOMAIN-SUFFIX,dotfacebook.net
DOMAIN-SUFFIX,expresswifi.com
DOMAIN-SUFFIX,faacebok.com
DOMAIN-SUFFIX,faacebook.com
DOMAIN-SUFFIX,faasbook.com
DOMAIN-SUFFIX,facbebook.com
DOMAIN-SUFFIX,facbeok.com
DOMAIN-SUFFIX,facboo.com
DOMAIN-SUFFIX,facbook.com
DOMAIN-SUFFIX,facbool.com
DOMAIN-SUFFIX,facboox.com
DOMAIN-SUFFIX,faccebook.com
DOMAIN-SUFFIX,faccebookk.com
DOMAIN-SUFFIX,facdbook.com
DOMAIN-SUFFIX,facdebook.com
DOMAIN-SUFFIX,face-book.com
DOMAIN-SUFFIX,faceabook.com
DOMAIN-SUFFIX,facebboc.com
DOMAIN-SUFFIX,facebbook.com
DOMAIN-SUFFIX,facebboook.com
DOMAIN-SUFFIX,facebcook.com
DOMAIN-SUFFIX,facebdok.com
DOMAIN-SUFFIX,facebgook.com
DOMAIN-SUFFIX,facebhook.com
DOMAIN-SUFFIX,facebkkk.com
DOMAIN-SUFFIX,facebo-ok.com
DOMAIN-SUFFIX,faceboak.com
DOMAIN-SUFFIX,facebock.com
DOMAIN-SUFFIX,facebocke.com
DOMAIN-SUFFIX,facebof.com
DOMAIN-SUFFIX,faceboik.com
DOMAIN-SUFFIX,facebok.com
DOMAIN-SUFFIX,facebokbook.com
DOMAIN-SUFFIX,facebokc.com
DOMAIN-SUFFIX,facebokk.com
DOMAIN-SUFFIX,facebokok.com
DOMAIN-SUFFIX,faceboks.com
DOMAIN-SUFFIX,facebol.com
DOMAIN-SUFFIX,facebolk.com
DOMAIN-SUFFIX,facebomok.com
DOMAIN-SUFFIX,faceboo.com
DOMAIN-SUFFIX,facebooa.com
DOMAIN-SUFFIX,faceboob.com
DOMAIN-SUFFIX,faceboobok.com
DOMAIN-SUFFIX,facebooc.com
DOMAIN-SUFFIX,faceboock.com
DOMAIN-SUFFIX,facebood.com
DOMAIN-SUFFIX,facebooe.com
DOMAIN-SUFFIX,faceboof.com
DOMAIN-SUFFIX,facebooi.com
DOMAIN-SUFFIX,facebooik.com
DOMAIN-SUFFIX,facebooik.org
DOMAIN-SUFFIX,facebooj.com
DOMAIN-SUFFIX,facebook-corp.com
DOMAIN-SUFFIX,facebook-covid-19.com
DOMAIN-SUFFIX,facebook-ebook.com
DOMAIN-SUFFIX,facebook-forum.com
DOMAIN-SUFFIX,facebook-hardware.com
DOMAIN-SUFFIX,facebook-inc.com
DOMAIN-SUFFIX,facebook-login.com
DOMAIN-SUFFIX,facebook-newsroom.com
DOMAIN-SUFFIX,facebook-newsroom.org
DOMAIN-SUFFIX,facebook-pmdcenter.com
DOMAIN-SUFFIX,facebook-pmdcenter.net
DOMAIN-SUFFIX,facebook-pmdcenter.org
DOMAIN-SUFFIX,facebook-privacy.com
DOMAIN-SUFFIX,facebook-program.com
DOMAIN-SUFFIX,facebook-studio.com
DOMAIN-SUFFIX,facebook-support.org
DOMAIN-SUFFIX,facebook-texas-holdem.com
DOMAIN-SUFFIX,facebook-texas-holdem.net
DOMAIN-SUFFIX,facebook.br
DOMAIN-SUFFIX,facebook.ca
DOMAIN-SUFFIX,facebook.cc
DOMAIN-SUFFIX,facebook.com
DOMAIN-SUFFIX,facebook.design
DOMAIN-SUFFIX,facebook.net
DOMAIN-SUFFIX,facebook.hu
DOMAIN-SUFFIX,facebook.in
DOMAIN-SUFFIX,fecebook.net
DOMAIN-SUFFIX,facebook.nl
DOMAIN-SUFFIX,facebook.org
DOMAIN-SUFFIX,facebook.se
DOMAIN-SUFFIX,facebook.shop
DOMAIN-SUFFIX,facebook.tv
DOMAIN-SUFFIX,facebook.us
DOMAIN-SUFFIX,facebook.wang
DOMAIN-SUFFIX,facebook123.org
DOMAIN-SUFFIX,facebook30.com
DOMAIN-SUFFIX,facebook30.net
DOMAIN-SUFFIX,facebook30.org
DOMAIN-SUFFIX,facebook4business.com
DOMAIN-SUFFIX,facebookads.com
DOMAIN-SUFFIX,facebookadvertisingsecrets.com
DOMAIN-SUFFIX,facebookatschool.com
DOMAIN-SUFFIX,facebookawards.com
DOMAIN-SUFFIX,facebookblueprint.net
DOMAIN-SUFFIX,facebookbrand.com
DOMAIN-SUFFIX,facebookbrand.net
DOMAIN-SUFFIX,facebookcanadianelectionintegrityinitiative.com
DOMAIN-SUFFIX,facebookcareer.com
DOMAIN-SUFFIX,facebookcheats.com
DOMAIN-SUFFIX,facebookck.com
DOMAIN-SUFFIX,facebookclub.com
DOMAIN-SUFFIX,facebookcom.com
DOMAIN-SUFFIX,facebookconsultant.org
DOMAIN-SUFFIX,facebookcoronavirus.com
DOMAIN-SUFFIX,facebookcovers.org
DOMAIN-SUFFIX,facebookcredits.info
DOMAIN-SUFFIX,facebookdating.net
DOMAIN-SUFFIX,facebookdusexe.org
DOMAIN-SUFFIX,facebookemail.com
DOMAIN-SUFFIX,facebookenespanol.com
DOMAIN-SUFFIX,facebookexchange.com
DOMAIN-SUFFIX,facebookexchange.net
DOMAIN-SUFFIX,facebookfacebook.com
DOMAIN-SUFFIX,facebookflow.com
DOMAIN-SUFFIX,facebookgames.com
DOMAIN-SUFFIX,facebookgraphsearch.com
DOMAIN-SUFFIX,facebookgraphsearch.info
DOMAIN-SUFFIX,facebookgroups.com
DOMAIN-SUFFIX,facebookhome.cc
DOMAIN-SUFFIX,facebookhome.com
DOMAIN-SUFFIX,facebookhome.info
DOMAIN-SUFFIX,facebookhub.com
DOMAIN-SUFFIX,facebooki.com
DOMAIN-SUFFIX,facebookinc.com
DOMAIN-SUFFIX,facebookland.com
DOMAIN-SUFFIX,facebooklikeexchange.com
DOMAIN-SUFFIX,facebooklive.com
DOMAIN-SUFFIX,facebooklivestaging.net
DOMAIN-SUFFIX,facebooklivestaging.org
DOMAIN-SUFFIX,facebooklogin.com
DOMAIN-SUFFIX,facebooklogin.info
DOMAIN-SUFFIX,facebookloginhelp.net
DOMAIN-SUFFIX,facebooklogs.com
DOMAIN-SUFFIX,facebookmail.com
DOMAIN-SUFFIX,facebookmail.tv
DOMAIN-SUFFIX,facebookmanager.info
DOMAIN-SUFFIX,facebookmarketing.info
DOMAIN-SUFFIX,facebookmarketingpartner.com
DOMAIN-SUFFIX,facebookmarketingpartners.com
DOMAIN-SUFFIX,facebookmobile.com
DOMAIN-SUFFIX,facebookmsn.com
DOMAIN-SUFFIX,facebooknews.com
DOMAIN-SUFFIX,facebooknfl.com
DOMAIN-SUFFIX,facebooknude.com
DOMAIN-SUFFIX,facebookofsex.com
DOMAIN-SUFFIX,facebookook.com
DOMAIN-SUFFIX,facebookpaper.com
DOMAIN-SUFFIX,facebookpay.com
DOMAIN-SUFFIX,facebookphonenumber.net
DOMAIN-SUFFIX,facebookphoto.com
DOMAIN-SUFFIX,facebookphotos.com
DOMAIN-SUFFIX,facebookpmdcenter.com
DOMAIN-SUFFIX,facebookpoke.net
DOMAIN-SUFFIX,facebookpoke.org
DOMAIN-SUFFIX,facebookpoker.info
DOMAIN-SUFFIX,facebookpokerchips.info
DOMAIN-SUFFIX,facebookporn.net
DOMAIN-SUFFIX,facebookporn.org
DOMAIN-SUFFIX,facebookporno.net
DOMAIN-SUFFIX,facebookportal.com
DOMAIN-SUFFIX,facebooks.com
DOMAIN-SUFFIX,facebooksafety.com
DOMAIN-SUFFIX,facebooksecurity.net
DOMAIN-SUFFIX,facebookshop.com
DOMAIN-SUFFIX,facebooksignup.net
DOMAIN-SUFFIX,facebooksite.net
DOMAIN-SUFFIX,facebookstories.com
DOMAIN-SUFFIX,facebookstudios.net
DOMAIN-SUFFIX,facebookstudios.org
DOMAIN-SUFFIX,facebooksupplier.com
DOMAIN-SUFFIX,facebooksuppliers.com
DOMAIN-SUFFIX,facebookswagemea.com
DOMAIN-SUFFIX,facebookswagstore.com
DOMAIN-SUFFIX,facebooksz.com
DOMAIN-SUFFIX,facebookthreads.net
DOMAIN-SUFFIX,facebooktv.net
DOMAIN-SUFFIX,facebooktv.org
DOMAIN-SUFFIX,facebookvacation.com
DOMAIN-SUFFIX,facebookw.com
DOMAIN-SUFFIX,facebookworld.com
DOMAIN-SUFFIX,facebool.com
DOMAIN-SUFFIX,facebool.info
DOMAIN-SUFFIX,facebooll.com
DOMAIN-SUFFIX,faceboom.com
DOMAIN-SUFFIX,faceboon.com
DOMAIN-SUFFIX,faceboonk.com
DOMAIN-SUFFIX,faceboooik.com
DOMAIN-SUFFIX,faceboook.com
DOMAIN-SUFFIX,faceboop.com
DOMAIN-SUFFIX,faceboot.com
DOMAIN-SUFFIX,faceboox.com
DOMAIN-SUFFIX,facebopk.com
DOMAIN-SUFFIX,facebpook.com
DOMAIN-SUFFIX,facebuk.com
DOMAIN-SUFFIX,facebuok.com
DOMAIN-SUFFIX,facebvook.com
DOMAIN-SUFFIX,facebyook.com
DOMAIN-SUFFIX,facebzook.com
DOMAIN-SUFFIX,facecbgook.com
DOMAIN-SUFFIX,facecbook.com
DOMAIN-SUFFIX,facecbook.org
DOMAIN-SUFFIX,facecook.com
DOMAIN-SUFFIX,facecook.org
DOMAIN-SUFFIX,facedbook.com
DOMAIN-SUFFIX,faceebok.com
DOMAIN-SUFFIX,faceebook.com
DOMAIN-SUFFIX,faceebot.com
DOMAIN-SUFFIX,facegbok.com
DOMAIN-SUFFIX,facegbook.com
DOMAIN-SUFFIX,faceobk.com
DOMAIN-SUFFIX,faceobok.com
DOMAIN-SUFFIX,faceobook.com
DOMAIN-SUFFIX,faceook.com
DOMAIN-SUFFIX,facerbooik.com
DOMAIN-SUFFIX,facerbook.com
DOMAIN-SUFFIX,facesbooc.com
DOMAIN-SUFFIX,facesounds.com
DOMAIN-SUFFIX,facetook.com
DOMAIN-SUFFIX,facevbook.com
DOMAIN-SUFFIX,facewbook.co
DOMAIN-SUFFIX,facewook.com
DOMAIN-SUFFIX,facfacebook.com
DOMAIN-SUFFIX,facfebook.com
DOMAIN-SUFFIX,fackebook.com
DOMAIN-SUFFIX,facnbook.com
DOMAIN-SUFFIX,facrbook.com
DOMAIN-SUFFIX,facvebook.com
DOMAIN-SUFFIX,facwebook.com
DOMAIN-SUFFIX,facxebook.com
DOMAIN-SUFFIX,fadebook.com
DOMAIN-SUFFIX,faebok.com
DOMAIN-SUFFIX,faebook.com
DOMAIN-SUFFIX,faebookc.com
DOMAIN-SUFFIX,faeboook.com
DOMAIN-SUFFIX,faecebok.com
DOMAIN-SUFFIX,faesebook.com
DOMAIN-SUFFIX,fafacebook.com
DOMAIN-SUFFIX,faicbooc.com
DOMAIN-SUFFIX,fasebokk.com
DOMAIN-SUFFIX,fasebook.com
DOMAIN-SUFFIX,faseboox.com
DOMAIN-SUFFIX,favebook.com
DOMAIN-SUFFIX,faycbok.com
DOMAIN-SUFFIX,fb.careers
DOMAIN-SUFFIX,fb.com
DOMAIN-SUFFIX,fb.me
DOMAIN-SUFFIX,fbacebook.com
DOMAIN-SUFFIX,fbbmarket.com
DOMAIN-SUFFIX,fbboostyourbusiness.com
DOMAIN-SUFFIX,fbcdn.com
DOMAIN-SUFFIX,fbcdn.net
DOMAIN-SUFFIX,fbfeedback.com
DOMAIN-SUFFIX,fbhome.com
DOMAIN-SUFFIX,fbidb.io
DOMAIN-SUFFIX,fbinc.com
DOMAIN-SUFFIX,fbinnovation.com
DOMAIN-SUFFIX,fbmarketing.com
DOMAIN-SUFFIX,fbreg.com
DOMAIN-SUFFIX,fbrpms.com
DOMAIN-SUFFIX,fbsbx.com
DOMAIN-SUFFIX,fbsbx.net
DOMAIN-SUFFIX,fbsupport-covid.net
DOMAIN-SUFFIX,fbthirdpartypixel.com
DOMAIN-SUFFIX,fbthirdpartypixel.net
DOMAIN-SUFFIX,fbthirdpartypixel.org
DOMAIN-SUFFIX,fburl.com
DOMAIN-SUFFIX,fbworkmail.com
DOMAIN-SUFFIX,fcacebook.com
DOMAIN-SUFFIX,fcaebook.com
DOMAIN-SUFFIX,fcebook.com
DOMAIN-SUFFIX,fcebookk.com
DOMAIN-SUFFIX,fcfacebook.com
DOMAIN-SUFFIX,fdacebook.info
DOMAIN-SUFFIX,feacboo.com
DOMAIN-SUFFIX,feacbook.com
DOMAIN-SUFFIX,feacbooke.com
DOMAIN-SUFFIX,feacebook.com
DOMAIN-SUFFIX,fecbbok.com
DOMAIN-SUFFIX,fecbooc.com
DOMAIN-SUFFIX,fecbook.com
DOMAIN-SUFFIX,feceboock.com
DOMAIN-SUFFIX,feceboox.com
DOMAIN-SUFFIX,fececbook.com
DOMAIN-SUFFIX,feook.com
DOMAIN-SUFFIX,ferabook.com
DOMAIN-SUFFIX,fescebook.com
DOMAIN-SUFFIX,fesebook.com
DOMAIN-SUFFIX,ffacebook.com
DOMAIN-SUFFIX,fgacebook.com
DOMAIN-SUFFIX,ficeboock.com
DOMAIN-SUFFIX,fmcebook.com
DOMAIN-SUFFIX,fnacebook.com
DOMAIN-SUFFIX,fosebook.com
DOMAIN-SUFFIX,fpacebook.com
DOMAIN-SUFFIX,fqcebook.com
DOMAIN-SUFFIX,fracebook.com
DOMAIN-SUFFIX,freeb.com
DOMAIN-SUFFIX,freebasics.com
DOMAIN-SUFFIX,freebasics.net
DOMAIN-SUFFIX,freebs.com
DOMAIN-SUFFIX,freefacebook.com
DOMAIN-SUFFIX,freefacebook.net
DOMAIN-SUFFIX,freefacebookads.net
DOMAIN-SUFFIX,freefblikes.com
DOMAIN-SUFFIX,freindfeed.com
DOMAIN-SUFFIX,friendbook.info
DOMAIN-SUFFIX,friendfed.com
DOMAIN-SUFFIX,friendfeed-api.com
DOMAIN-SUFFIX,friendfeed-media.com
DOMAIN-SUFFIX,friendfeed.com
DOMAIN-SUFFIX,friendfeedmedia.com
DOMAIN-SUFFIX,fsacebok.com
DOMAIN-SUFFIX,fscebook.com
DOMAIN-SUFFIX,fundraisingwithfacebook.com
DOMAIN-SUFFIX,funnyfacebook.org
DOMAIN-SUFFIX,futureofbusinesssurvey.org
DOMAIN-SUFFIX,gacebook.com
DOMAIN-SUFFIX,gameroom.com
DOMAIN-SUFFIX,gfacecbook.com
DOMAIN-SUFFIX,groups.com
DOMAIN-SUFFIX,hackerfacebook.com
DOMAIN-SUFFIX,hackfacebook.com
DOMAIN-SUFFIX,hackfacebookid.com
DOMAIN-SUFFIX,hifacebook.info
DOMAIN-SUFFIX,howtohackfacebook-account.com
DOMAIN-SUFFIX,hsfacebook.com
DOMAIN-SUFFIX,httpfacebook.com
DOMAIN-SUFFIX,httpsfacebook.com
DOMAIN-SUFFIX,httpwwwfacebook.com
DOMAIN-SUFFIX,i.org
DOMAIN-SUFFIX,internet.org
DOMAIN-SUFFIX,klik.me
DOMAIN-SUFFIX,liverail.com
DOMAIN-SUFFIX,liverail.tv
DOMAIN-SUFFIX,login-account.net
DOMAIN-SUFFIX,markzuckerberg.com
DOMAIN-SUFFIX,midentsolutions.com
DOMAIN-SUFFIX,mobilefacebook.com
DOMAIN-SUFFIX,moneywithfacebook.com
DOMAIN-SUFFIX,myfbfans.com
DOMAIN-SUFFIX,newsfeed.com
DOMAIN-SUFFIX,nextstop.com
DOMAIN-SUFFIX,online-deals.net
DOMAIN-SUFFIX,opencreate.org
DOMAIN-SUFFIX,reachtheworldonfacebook.com
DOMAIN-SUFFIX,rocksdb.org
DOMAIN-SUFFIX,shopfacebook.com
DOMAIN-SUFFIX,sportsfacebook.com
DOMAIN-SUFFIX,sportstream.com
DOMAIN-SUFFIX,supportfacebook.com
DOMAIN-SUFFIX,terragraph.com
DOMAIN-SUFFIX,thefacebook.com
DOMAIN-SUFFIX,thefacebook.net
DOMAIN-SUFFIX,thefind.com
DOMAIN-SUFFIX,toplayerserver.com
DOMAIN-SUFFIX,viewpointsfromfacebook.com
DOMAIN-SUFFIX,whyfacebook.com
DOMAIN-SUFFIX,worldhack.com
DOMAIN-SUFFIX,www-facebook.com
DOMAIN-SUFFIX,wwwfacebok.com
DOMAIN-SUFFIX,wwwfacebook.com
DOMAIN-SUFFIX,wwwmfacebook.com
DOMAIN-SUFFIX,zuckerberg.com
DOMAIN-SUFFIX,zuckerberg.net
DOMAIN-SUFFIX,facebookwork.com
DOMAIN-SUFFIX,redkix.com
DOMAIN-SUFFIX,workplace.com
DOMAIN-SUFFIX,workplaceusecases.com
DOMAIN,fbcdn-a.akamaihd.net

# > Facebook Dev
DOMAIN-SUFFIX,accountkit.com
DOMAIN-SUFFIX,atscaleconference.com
DOMAIN-SUFFIX,botorch.org
DOMAIN-SUFFIX,buck.build
DOMAIN-SUFFIX,buckbuild.com
DOMAIN-SUFFIX,componentkit.org
DOMAIN-SUFFIX,draftjs.org
DOMAIN-SUFFIX,f8.com
DOMAIN-SUFFIX,facebookappcenter.info
DOMAIN-SUFFIX,facebookappcenter.net
DOMAIN-SUFFIX,facebookappcenter.org
DOMAIN-SUFFIX,facebookconnect.com
DOMAIN-SUFFIX,facebookdevelopergarage.com
DOMAIN-SUFFIX,faciometrics.com
DOMAIN-SUFFIX,fasttext.cc
DOMAIN-SUFFIX,fbf8.com
DOMAIN-SUFFIX,fbinfer.com
DOMAIN-SUFFIX,fblitho.com
DOMAIN-SUFFIX,fbredex.com
DOMAIN-SUFFIX,fbrell.com
DOMAIN-SUFFIX,flow.dev
DOMAIN-SUFFIX,flow.org
DOMAIN-SUFFIX,flowtype.org
DOMAIN-SUFFIX,frescolib.org
DOMAIN-SUFFIX,hacklang.org
DOMAIN-SUFFIX,hhvm.com
DOMAIN-SUFFIX,makeitopen.com
DOMAIN-SUFFIX,mcrouter.net
DOMAIN-SUFFIX,mcrouter.org
DOMAIN-SUFFIX,messengerdevelopers.com
DOMAIN-SUFFIX,ogp.me
DOMAIN-SUFFIX,opengraphprotocol.com
DOMAIN-SUFFIX,opengraphprotocol.org
DOMAIN-SUFFIX,parse.com
DOMAIN-SUFFIX,pyrobot.org
DOMAIN-SUFFIX,react.com
DOMAIN-SUFFIX,reactjs.com
DOMAIN-SUFFIX,reactjs.org
DOMAIN-SUFFIX,recoiljs.org
DOMAIN-SUFFIX,rocksdb.com
DOMAIN-SUFFIX,rocksdb.net
DOMAIN-SUFFIX,rocksdb.org
DOMAIN-SUFFIX,yogalayout.com
DOMAIN,developers.facebook.com

# > Telegram
DOMAIN-SUFFIX,comments.app
DOMAIN-SUFFIX,contest.com
DOMAIN-SUFFIX,graph.org
DOMAIN-SUFFIX,quiz.directory
DOMAIN-SUFFIX,stel.com
DOMAIN-SUFFIX,t.me
DOMAIN-SUFFIX,tdesktop.com
DOMAIN-SUFFIX,telega.one
DOMAIN-SUFFIX,telegra.ph
DOMAIN-SUFFIX,telegram.dog
DOMAIN-SUFFIX,telegram.me
DOMAIN-SUFFIX,telegram.org
DOMAIN-SUFFIX,telegram.space
DOMAIN-SUFFIX,telegramdownload.com
DOMAIN-SUFFIX,telesco.pe
DOMAIN-SUFFIX,tg.dev
DOMAIN-SUFFIX,tx.me
DOMAIN-SUFFIX,usercontent.dev

IP-CIDR,91.108.56.0/22,no-resolve
IP-CIDR,91.108.4.0/22,no-resolve
IP-CIDR,91.108.8.0/22,no-resolve
IP-CIDR,91.108.16.0/22,no-resolve
IP-CIDR,91.108.12.0/22,no-resolve
IP-CIDR,149.154.160.0/20,no-resolve
IP-CIDR,91.105.192.0/23,no-resolve
IP-CIDR,91.108.20.0/22,no-resolve
IP-CIDR,185.76.151.0/24,no-resolve
IP-CIDR6,2001:b28:f23d::/48,no-resolve
IP-CIDR6,2001:b28:f23f::/48,no-resolve
IP-CIDR6,2001:67c:4e8::/48,no-resolve
IP-CIDR6,2001:b28:f23c::/48,no-resolve
IP-CIDR6,2a0a:f280::/32,no-resolve

IP-CIDR,109.239.140.0/24,no-resolve
IP-CIDR,149.154.164.0/22,no-resolve
IP-CIDR,149.154.172.0/22,no-resolve
IP-CIDR,5.28.192.0/18,no-resolve
IP-CIDR,95.161.64.0/20,no-resolve

# > Youtube
DOMAIN-SUFFIX,youtube
DOMAIN-SUFFIX,ggpht.com
DOMAIN-SUFFIX,googlevideo.com
DOMAIN-SUFFIX,withyoutube.com
DOMAIN-SUFFIX,youtu.be
DOMAIN-SUFFIX,youtube-nocookie.com
DOMAIN-SUFFIX,youtube-ui.l.google.com
DOMAIN-SUFFIX,youtube.com
DOMAIN-SUFFIX,youtube.com.sg
DOMAIN-SUFFIX,youtube.sg
DOMAIN-SUFFIX,youtubeeducation.com
DOMAIN-SUFFIX,youtubefanfest.com
DOMAIN-SUFFIX,youtubegaming.com
DOMAIN-SUFFIX,youtubego.com
DOMAIN-SUFFIX,youtubekids.com
DOMAIN-SUFFIX,youtubemobilesupport.com
DOMAIN-SUFFIX,yt.be
DOMAIN-SUFFIX,ytimg.com
DOMAIN-SUFFIX,googleapis.com

# > Dropbox
DOMAIN-SUFFIX,db.tt
DOMAIN-SUFFIX,dropbox-dns.com
DOMAIN-SUFFIX,dropbox.com
DOMAIN-SUFFIX,dropbox.tech
DOMAIN-SUFFIX,dropboxapi.com
DOMAIN-SUFFIX,dropboxbusiness.com
DOMAIN-SUFFIX,dropboxcaptcha.com
DOMAIN-SUFFIX,dropboxforum.com
DOMAIN-SUFFIX,dropboxforums.com
DOMAIN-SUFFIX,dropboxinsiders.com
DOMAIN-SUFFIX,dropboxmail.com
DOMAIN-SUFFIX,dropboxpartners.com
DOMAIN-SUFFIX,dropboxstatic.com
DOMAIN-SUFFIX,dropboxusercontent.com
DOMAIN-SUFFIX,getdropbox.com

# > Github
DOMAIN-SUFFIX,npm.community
DOMAIN-SUFFIX,npmjs.com
DOMAIN-SUFFIX,npmjs.org
DOMAIN-SUFFIX,atom.io
DOMAIN-SUFFIX,dependabot.com
DOMAIN-SUFFIX,ghcr.io
DOMAIN-SUFFIX,git.io
DOMAIN-SUFFIX,github.blog
DOMAIN-SUFFIX,github.com
DOMAIN-SUFFIX,github.community
DOMAIN-SUFFIX,github.dev
DOMAIN-SUFFIX,github.io
DOMAIN-SUFFIX,githubapp.com
DOMAIN-SUFFIX,githubassets.com
DOMAIN-SUFFIX,githubhackathon.com
DOMAIN-SUFFIX,githubpreview.dev
DOMAIN-SUFFIX,githubstatus.com
DOMAIN-SUFFIX,githubuniverse.com
DOMAIN-SUFFIX,githubusercontent.com
DOMAIN-SUFFIX,myoctocat.com
DOMAIN-SUFFIX,opensource.guide
DOMAIN-SUFFIX,thegithubshop.com

# > Gitlab
DOMAIN-SUFFIX,gitlab.com
DOMAIN-SUFFIX,gitlab.io
DOMAIN-SUFFIX,gitlab.net
DOMAIN-SUFFIX,gitlab-static.net

# > GitBook
DOMAIN-SUFFIX,gitbook.com
DOMAIN-SUFFIX,gitbook.io

# > JSDelivr
DOMAIN-SUFFIX,jsdelivr.com
DOMAIN-SUFFIX,jsdelivr.net
DOMAIN-SUFFIX,esm.run

# > StackExchange
DOMAIN-SUFFIX,askubuntu.com
DOMAIN-SUFFIX,blogoverflow.com
DOMAIN-SUFFIX,codeforaliving.io
DOMAIN-SUFFIX,mathoverflow.net
DOMAIN-SUFFIX,serverfault.com
DOMAIN-SUFFIX,sstatic.net
DOMAIN-SUFFIX,stackapps.com
DOMAIN-SUFFIX,stackauth.com
DOMAIN-SUFFIX,stackexchange.com
DOMAIN-SUFFIX,stackmod.blog
DOMAIN-SUFFIX,stackoverflow.blog
DOMAIN-SUFFIX,stackoverflow.co
DOMAIN-SUFFIX,stackoverflow.com
DOMAIN-SUFFIX,stackoverflow.email
DOMAIN-SUFFIX,stackoverflowbusiness.com
DOMAIN-SUFFIX,stackoverflowcareers.com
DOMAIN-SUFFIX,stacksnippets.net
DOMAIN-SUFFIX,superuser.com
DOMAIN-SUFFIX,tex-talk.net
DOMAIN-SUFFIX,thesffblog.com

# > Python
DOMAIN-SUFFIX,pycon.org
DOMAIN-SUFFIX,pypa.io
DOMAIN-SUFFIX,pypi.io
DOMAIN-SUFFIX,pypi.org
DOMAIN-SUFFIX,python.org
DOMAIN-SUFFIX,pythonhosted.org
DOMAIN-SUFFIX,piwheels.org

# > Javascript
DOMAIN-SUFFIX,javascript.info

# > Wikimedia
DOMAIN-SUFFIX,mediawiki.org
DOMAIN-SUFFIX,wikibooks.org
DOMAIN-SUFFIX,wikidata.org
DOMAIN-SUFFIX,wikimediafoundation.org
DOMAIN-SUFFIX,wikimedia.org
DOMAIN-SUFFIX,wikinews.org
DOMAIN-SUFFIX,wikipedia.org
DOMAIN-SUFFIX,wikiquote.org
DOMAIN-SUFFIX,wikisource.org
DOMAIN-SUFFIX,wikiversity.org
DOMAIN-SUFFIX,wikivoyage.org
DOMAIN-SUFFIX,wiktionary.org
DOMAIN-SUFFIX,wmfusercontent.org
DOMAIN-SUFFIX,w.wiki
DOMAIN-SUFFIX,toolforge.org
DOMAIN-SUFFIX,wikimediacloud.org
DOMAIN-SUFFIX,wmcloud.org
DOMAIN-SUFFIX,wmflabs.org
  
# > wikiHow
DOMAIN-SUFFIX,wikihow.com

# > Reddit
DOMAIN-SUFFIX,reddit.com
DOMAIN-SUFFIX,redditstatic.com
DOMAIN-SUFFIX,redditmail.com
DOMAIN-SUFFIX,redditmedia.com
DOMAIN-SUFFIX,redd.it

# > hCaptcha
DOMAIN-SUFFIX,botstop.com
DOMAIN-SUFFIX,hcaptcha.com
DOMAIN-SUFFIX,hcaptchastatus.com

# > Imgur
DOMAIN-SUFFIX,imgur.com
DOMAIN-SUFFIX,imgurinc.com

# > Google
DOMAIN-SUFFIX,android.com
DOMAIN-SUFFIX,androidify.com

DOMAIN-SUFFIX,blogger.com
DOMAIN-SUFFIX,blogblog.com
DOMAIN-SUFFIX,blogspot.com
DOMAIN-SUFFIX,blogspot.sg

DOMAIN-SUFFIX,dart.dev
DOMAIN-SUFFIX,dartlang.org
DOMAIN-SUFFIX,dartpad.dev

DOMAIN-SUFFIX,fastlane.ci
DOMAIN-SUFFIX,fastlane.tools

DOMAIN-SUFFIX,flutter.dev
DOMAIN-SUFFIX,flutterapp.com

DOMAIN-SUFFIX,go-lang.com
DOMAIN-SUFFIX,go-lang.net
DOMAIN-SUFFIX,go-lang.org
DOMAIN-SUFFIX,go.dev
DOMAIN-SUFFIX,godoc.org
DOMAIN-SUFFIX,golang.com
DOMAIN-SUFFIX,golang.net
DOMAIN-SUFFIX,golang.org

DOMAIN-SUFFIX,2mdn.net
DOMAIN-SUFFIX,admob.com
DOMAIN-SUFFIX,ads.youtube.com
DOMAIN-SUFFIX,adsense.com
DOMAIN-SUFFIX,adsensecustomsearchads.com
DOMAIN-SUFFIX,adsenseformobileapps.com
DOMAIN-SUFFIX,adservice.google.com
DOMAIN-SUFFIX,advertisercommunity.com
DOMAIN-SUFFIX,advertiserscommunity.com
DOMAIN-SUFFIX,adwords-community.com
DOMAIN-SUFFIX,adwords.com
DOMAIN-SUFFIX,adwordsexpress.com
DOMAIN-SUFFIX,app-measurement.com
DOMAIN-SUFFIX,clickserver.googleads.com
DOMAIN-SUFFIX,doubleclick.com
DOMAIN-SUFFIX,doubleclick.net
DOMAIN-SUFFIX,google-analytics.com
DOMAIN-SUFFIX,googleadapis.com
DOMAIN-SUFFIX,googleadservices.com
DOMAIN-SUFFIX,googleanalytics.com
DOMAIN-SUFFIX,googleoptimize.com
DOMAIN-SUFFIX,googlesyndication.com
DOMAIN-SUFFIX,googletagmanager.com
DOMAIN-SUFFIX,googletagservices.com
DOMAIN-SUFFIX,googletraveladservices.com
DOMAIN-SUFFIX,urchin.com

DOMAIN-SUFFIX,charlestonroadregistry.com
DOMAIN-SUFFIX,registry.google
DOMAIN-SUFFIX,get.app
DOMAIN-SUFFIX,get.dev
DOMAIN-SUFFIX,get.how
DOMAIN-SUFFIX,get.page
DOMAIN-SUFFIX,iam.soy
DOMAIN-SUFFIX,xn--p8j9a0d9c9a.xn--q9jyb4c

DOMAIN,scholar.google.com
DOMAIN,scholar.google.com.sg
DOMAIN,scholar.l.google.com

DOMAIN-SUFFIX,pki.goog

DOMAIN-SUFFIX,kaggle.com
DOMAIN-SUFFIX,kaggle.io

DOMAIN-SUFFIX,deps.dev
DOMAIN-SUFFIX,deps.info
DOMAIN-SUFFIX,opensourceinsight.dev
DOMAIN-SUFFIX,opensourceinsights.dev

DOMAIN-SUFFIX,polymer-project.org
DOMAIN-SUFFIX,polymerproject.org

DOMAIN-SUFFIX,v8.dev
DOMAIN-SUFFIX,v8project.org

DOMAIN-SUFFIX,and
DOMAIN-SUFFIX,chrome
DOMAIN-SUFFIX,dclk
DOMAIN-SUFFIX,gbiz
DOMAIN-SUFFIX,gle
DOMAIN-SUFFIX,gmail
DOMAIN-SUFFIX,goo
DOMAIN-SUFFIX,goog
DOMAIN-SUFFIX,google
DOMAIN-SUFFIX,guge
DOMAIN-SUFFIX,hangout
DOMAIN-SUFFIX,nexus
DOMAIN-SUFFIX,xn--flw351e
DOMAIN-SUFFIX,xn--qcka1pmc
DOMAIN-SUFFIX,google.com
DOMAIN-SUFFIX,google.com.sg
DOMAIN-SUFFIX,0emm.com
DOMAIN-SUFFIX,1e100.net
DOMAIN-SUFFIX,1ucrs.com
DOMAIN-SUFFIX,466453.com
DOMAIN-SUFFIX,abc.xyz
DOMAIN-SUFFIX,adgoogle.net
DOMAIN-SUFFIX,admeld.com
DOMAIN-SUFFIX,angulardart.org
DOMAIN-SUFFIX,api.ai
DOMAIN-SUFFIX,apigee.com
DOMAIN-SUFFIX,appbridge.ca
DOMAIN-SUFFIX,appbridge.io
DOMAIN-SUFFIX,appbridge.it
DOMAIN-SUFFIX,appspot.com
DOMAIN-SUFFIX,apture.com
DOMAIN-SUFFIX,area120.com
DOMAIN-SUFFIX,asp-cc.com
DOMAIN-SUFFIX,autodraw.com
DOMAIN-SUFFIX,bandpage.com
DOMAIN-SUFFIX,baselinestudy.com
DOMAIN-SUFFIX,baselinestudy.org
DOMAIN-SUFFIX,bazel.build
DOMAIN-SUFFIX,bdn.dev
DOMAIN-SUFFIX,beatthatquote.com
DOMAIN-SUFFIX,blink.org
DOMAIN-SUFFIX,brocaproject.com
DOMAIN-SUFFIX,brotli.org
DOMAIN-SUFFIX,bumpshare.com
DOMAIN-SUFFIX,bumptop.ca
DOMAIN-SUFFIX,bumptop.com
DOMAIN-SUFFIX,bumptop.net
DOMAIN-SUFFIX,bumptop.org
DOMAIN-SUFFIX,bumptunes.com
DOMAIN-SUFFIX,campuslondon.com
DOMAIN-SUFFIX,certificate-transparency.org
DOMAIN-SUFFIX,chrome.com
DOMAIN-SUFFIX,chromebook.com
DOMAIN-SUFFIX,chromecast.com
DOMAIN-SUFFIX,chromeos.dev
DOMAIN-SUFFIX,chromium.org
DOMAIN-SUFFIX,chronicle.security
DOMAIN-SUFFIX,chroniclesec.com
DOMAIN-SUFFIX,cloudburstresearch.com
DOMAIN-SUFFIX,cloudfunctions.net
DOMAIN-SUFFIX,cloudproxy.app
DOMAIN-SUFFIX,cloudrobotics.com
DOMAIN-SUFFIX,cobrasearch.com
DOMAIN-SUFFIX,codespot.com
DOMAIN-SUFFIX,conscrypt.com
DOMAIN-SUFFIX,conscrypt.org
DOMAIN-SUFFIX,cookiechoices.org
DOMAIN-SUFFIX,coova.com
DOMAIN-SUFFIX,coova.net
DOMAIN-SUFFIX,coova.org
DOMAIN-SUFFIX,crossmediapanel.com
DOMAIN-SUFFIX,crr.com
DOMAIN-SUFFIX,cs4hs.com
DOMAIN-SUFFIX,dartsearch.net
DOMAIN-SUFFIX,dataliberation.org
DOMAIN-SUFFIX,debug.com
DOMAIN-SUFFIX,debugproject.com
DOMAIN-SUFFIX,deepmind.com
DOMAIN-SUFFIX,devsitetest.how
DOMAIN-SUFFIX,dialogflow.com
DOMAIN-SUFFIX,digitalassetlinks.org
DOMAIN-SUFFIX,episodic.com
DOMAIN-SUFFIX,feedburner.com
DOMAIN-SUFFIX,fflick.com
DOMAIN-SUFFIX,financeleadsonline.com
DOMAIN-SUFFIX,firebaseapp.com
DOMAIN-SUFFIX,firebaseio.com
DOMAIN-SUFFIX,foofle.com
DOMAIN-SUFFIX,froogle.com
DOMAIN-SUFFIX,fuchsia.dev
DOMAIN-SUFFIX,g-tun.com
DOMAIN-SUFFIX,g.cn
DOMAIN-SUFFIX,g.co
DOMAIN-SUFFIX,g.dev
DOMAIN-SUFFIX,g.page
DOMAIN-SUFFIX,gateway.dev
DOMAIN-SUFFIX,gcr.io
DOMAIN-SUFFIX,gerritcodereview.com
DOMAIN-SUFFIX,getbumptop.com
DOMAIN-SUFFIX,ggoogle.com
DOMAIN-SUFFIX,gipscorp.com
DOMAIN-SUFFIX,gkecnapps.cn
DOMAIN-SUFFIX,globaledu.org
DOMAIN-SUFFIX,gmail.com
DOMAIN-SUFFIX,gmodules.com
DOMAIN-SUFFIX,gogle.com
DOMAIN-SUFFIX,gogole.com
DOMAIN-SUFFIX,gonglchuangl.net
DOMAIN-SUFFIX,goo.gl
DOMAIN-SUFFIX,googel.com
DOMAIN-SUFFIX,googil.com
DOMAIN-SUFFIX,googl.com
DOMAIN-SUFFIX,google-syndication.com
DOMAIN-SUFFIX,google.berlin
DOMAIN-SUFFIX,google.dev
DOMAIN-SUFFIX,google.net
DOMAIN-SUFFIX,google.org
DOMAIN-SUFFIX,google.ventures
DOMAIN-SUFFIX,googleacquisitionmigration.com
DOMAIN-SUFFIX,googleapis.cn
DOMAIN-SUFFIX,googleapis.com
DOMAIN-SUFFIX,googleapps.com
DOMAIN-SUFFIX,googlearth.com
DOMAIN-SUFFIX,googleblog.com
DOMAIN-SUFFIX,googlebot.com
DOMAIN-SUFFIX,googlecapital.com
DOMAIN-SUFFIX,googlecert.net
DOMAIN-SUFFIX,googlecnapps.cn
DOMAIN-SUFFIX,googlecode.com
DOMAIN-SUFFIX,googlecommerce.com
DOMAIN-SUFFIX,googlecompare.co.uk
DOMAIN-SUFFIX,googledanmark.com
DOMAIN-SUFFIX,googledomains.com
DOMAIN-SUFFIX,googledrive.com
DOMAIN-SUFFIX,googlee.com
DOMAIN-SUFFIX,googleearth.com
DOMAIN-SUFFIX,googlefiber.net
DOMAIN-SUFFIX,googlefinland.com
DOMAIN-SUFFIX,googlemail.com
DOMAIN-SUFFIX,googlemaps.com
DOMAIN-SUFFIX,googlepagecreator.com
DOMAIN-SUFFIX,googlephotos.com
DOMAIN-SUFFIX,googleplay.com
DOMAIN-SUFFIX,googleplus.com
DOMAIN-SUFFIX,googlesource.com
DOMAIN-SUFFIX,googlestore.com
DOMAIN-SUFFIX,googlesverige.com
DOMAIN-SUFFIX,googleusercontent.com
DOMAIN-SUFFIX,googleventures.com
DOMAIN-SUFFIX,googlr.com
DOMAIN-SUFFIX,goolge.com
DOMAIN-SUFFIX,gooogle.com
DOMAIN-SUFFIX,gridaware.app
DOMAIN-SUFFIX,gsrc.io
DOMAIN-SUFFIX,gstatic.cn
DOMAIN-SUFFIX,gstatic.com
DOMAIN-SUFFIX,gstaticcnapps.cn
DOMAIN-SUFFIX,gsuite.com
DOMAIN-SUFFIX,gv.com
DOMAIN-SUFFIX,gvt0.com
DOMAIN-SUFFIX,gvt1.com
DOMAIN-SUFFIX,gvt2.com
DOMAIN-SUFFIX,gvt3.com
DOMAIN-SUFFIX,gvt5.com
DOMAIN-SUFFIX,gvt6.com
DOMAIN-SUFFIX,gvt7.com
DOMAIN-SUFFIX,gvt9.com
DOMAIN-SUFFIX,hdrplusdata.org
DOMAIN-SUFFIX,hindiweb.com
DOMAIN-SUFFIX,howtogetmo.co.uk
DOMAIN-SUFFIX,html5rocks.com
DOMAIN-SUFFIX,hwgo.com
DOMAIN-SUFFIX,iamremarkable.org
DOMAIN-SUFFIX,igoogle.com
DOMAIN-SUFFIX,impermium.com
DOMAIN-SUFFIX,j2objc.org
DOMAIN-SUFFIX,jibemobile.com
DOMAIN-SUFFIX,keyhole.com
DOMAIN-SUFFIX,keytransparency.com
DOMAIN-SUFFIX,keytransparency.foo
DOMAIN-SUFFIX,keytransparency.org
DOMAIN-SUFFIX,lanternal.com
DOMAIN-SUFFIX,like.com
DOMAIN-SUFFIX,madewithcode.com
DOMAIN-SUFFIX,material.io
DOMAIN-SUFFIX,mdialog.com
DOMAIN-SUFFIX,meet.new
DOMAIN-SUFFIX,mfg-inspector.com
DOMAIN-SUFFIX,mobileview.page
DOMAIN-SUFFIX,moodstocks.com
DOMAIN-SUFFIX,near.by
DOMAIN-SUFFIX,nest.com
DOMAIN-SUFFIX,nomulus.foo
DOMAIN-SUFFIX,oauthz.com
DOMAIN-SUFFIX,on.here
DOMAIN-SUFFIX,on2.com
DOMAIN-SUFFIX,onefifteen.net
DOMAIN-SUFFIX,onefifteen.org
DOMAIN-SUFFIX,oneworldmanystories.com
DOMAIN-SUFFIX,openthread.io
DOMAIN-SUFFIX,openweave.io
DOMAIN-SUFFIX,orbitera.com
DOMAIN-SUFFIX,page.link
DOMAIN-SUFFIX,pagespeedmobilizer.com
DOMAIN-SUFFIX,pageview.mobi
DOMAIN-SUFFIX,panoramio.com
DOMAIN-SUFFIX,partylikeits1986.org
DOMAIN-SUFFIX,paxlicense.org
DOMAIN-SUFFIX,picasa.com
DOMAIN-SUFFIX,picasaweb.com
DOMAIN-SUFFIX,picasaweb.net
DOMAIN-SUFFIX,picasaweb.org
DOMAIN-SUFFIX,picnik.com
DOMAIN-SUFFIX,pittpatt.com
DOMAIN-SUFFIX,pixate.com
DOMAIN-SUFFIX,postini.com
DOMAIN-SUFFIX,privacysandbox.com
DOMAIN-SUFFIX,projectara.com
DOMAIN-SUFFIX,projectbaseline.com
DOMAIN-SUFFIX,publishproxy.com
DOMAIN-SUFFIX,questvisual.com
DOMAIN-SUFFIX,quickoffice.com
DOMAIN-SUFFIX,quiksee.com
DOMAIN-SUFFIX,revolv.com
DOMAIN-SUFFIX,ridepenguin.com
DOMAIN-SUFFIX,run.app
DOMAIN-SUFFIX,savethedate.foo
DOMAIN-SUFFIX,saynow.com
DOMAIN-SUFFIX,schemer.com
DOMAIN-SUFFIX,screenwisetrends.com
DOMAIN-SUFFIX,screenwisetrendspanel.com
DOMAIN-SUFFIX,snapseed.com
DOMAIN-SUFFIX,solveforx.com
DOMAIN-SUFFIX,stadia.dev
DOMAIN-SUFFIX,stcroixmosquito.com
DOMAIN-SUFFIX,stcroixmosquitoproject.com
DOMAIN-SUFFIX,studywatchbyverily.com
DOMAIN-SUFFIX,studywatchbyverily.org
DOMAIN-SUFFIX,stxmosquito.com
DOMAIN-SUFFIX,stxmosquitoproject.com
DOMAIN-SUFFIX,stxmosquitoproject.net
DOMAIN-SUFFIX,stxmosquitoproject.org
DOMAIN-SUFFIX,synergyse.com
DOMAIN-SUFFIX,tensorflow.org
DOMAIN-SUFFIX,tfhub.dev
DOMAIN-SUFFIX,thecleversense.com
DOMAIN-SUFFIX,thegooglestore.com
DOMAIN-SUFFIX,thinkquarterly.co.uk
DOMAIN-SUFFIX,thinkquarterly.com
DOMAIN-SUFFIX,thinkwithgoogle.com
DOMAIN-SUFFIX,tiltbrush.com
DOMAIN-SUFFIX,txcloud.net
DOMAIN-SUFFIX,txvia.com
DOMAIN-SUFFIX,unfiltered.news
DOMAIN-SUFFIX,useplannr.com
DOMAIN-SUFFIX,usvimosquito.com
DOMAIN-SUFFIX,usvimosquitoproject.com
DOMAIN-SUFFIX,velostrata.com
DOMAIN-SUFFIX,verily.com
DOMAIN-SUFFIX,verilylifesciences.com
DOMAIN-SUFFIX,verilystudyhub.com
DOMAIN-SUFFIX,verilystudywatch.com
DOMAIN-SUFFIX,verilystudywatch.org
DOMAIN-SUFFIX,wallet.com
DOMAIN-SUFFIX,waymo.com
DOMAIN-SUFFIX,waze.com
DOMAIN-SUFFIX,web.app
DOMAIN-SUFFIX,web.dev
DOMAIN-SUFFIX,webappfieldguide.com
DOMAIN-SUFFIX,webmproject.org
DOMAIN-SUFFIX,webpkgcache.com
DOMAIN-SUFFIX,webrtc.org
DOMAIN-SUFFIX,weltweitwachsen.de
DOMAIN-SUFFIX,whatbrowser.org
DOMAIN-SUFFIX,widevine.com
DOMAIN-SUFFIX,withgoogle.com
DOMAIN-SUFFIX,womenwill.com
DOMAIN-SUFFIX,womenwill.com.br
DOMAIN-SUFFIX,womenwill.id
DOMAIN-SUFFIX,womenwill.in
DOMAIN-SUFFIX,womenwill.mx
DOMAIN-SUFFIX,x.company
DOMAIN-SUFFIX,x.team
DOMAIN-SUFFIX,xn--9kr7l.com
DOMAIN-SUFFIX,xn--9trs65b.com
DOMAIN-SUFFIX,xn--flw351e.com
DOMAIN-SUFFIX,xn--ggle-55da.com
DOMAIN-SUFFIX,xn--gogl-0nd52e.com
DOMAIN-SUFFIX,xn--gogl-1nd42e.com
DOMAIN-SUFFIX,xn--ngstr-lra8j.com
DOMAIN-SUFFIX,xplr.co
DOMAIN-SUFFIX,zukunftswerkstatt.de

# > Microsoft
DOMAIN-SUFFIX,azure-dns.com
DOMAIN-SUFFIX,azure-dns.info
DOMAIN-SUFFIX,azure-dns.net
DOMAIN-SUFFIX,azure-dns.org
DOMAIN-SUFFIX,azure-mobile.net
DOMAIN-SUFFIX,azure-sphere.com
DOMAIN-SUFFIX,azure-test.net
DOMAIN-SUFFIX,azure.com
DOMAIN-SUFFIX,azure.net
DOMAIN-SUFFIX,azurecomcdn.net
DOMAIN-SUFFIX,azurecontainer.io
DOMAIN-SUFFIX,azurecosmos.net
DOMAIN-SUFFIX,azurecosmosdb.com
DOMAIN-SUFFIX,azurecosmosdb.info
DOMAIN-SUFFIX,azurecosmosdb.net
DOMAIN-SUFFIX,azuredatabricks.net
DOMAIN-SUFFIX,azuredevopslaunch.com
DOMAIN-SUFFIX,azuredigitaltwin.com
DOMAIN-SUFFIX,azuredigitaltwins.com
DOMAIN-SUFFIX,azuredigitaltwins.net
DOMAIN-SUFFIX,azuredns-prd.info
DOMAIN-SUFFIX,azuredns-prd.org
DOMAIN-SUFFIX,azureedge-test.net
DOMAIN-SUFFIX,azureedge.net
DOMAIN-SUFFIX,azureiotcentral.com
DOMAIN-SUFFIX,azureiotsolutions.com
DOMAIN-SUFFIX,azureiotsuite.com
DOMAIN-SUFFIX,azureplanetscale.info
DOMAIN-SUFFIX,azureplanetscale.net
DOMAIN-SUFFIX,azureserviceprofiler.com
DOMAIN-SUFFIX,azuresmartspaces.net
DOMAIN-SUFFIX,azurestackvalidation.com
DOMAIN-SUFFIX,azurewebsites.net
DOMAIN-SUFFIX,cosmosdb.info
DOMAIN-SUFFIX,cosmosdb.net
DOMAIN-SUFFIX,devopsms.com
DOMAIN-SUFFIX,gotcosmos.com
DOMAIN-SUFFIX,microsofteca.com
DOMAIN-SUFFIX,microsoftiotcentral.com
DOMAIN-SUFFIX,serverlesslibrary.net
DOMAIN-SUFFIX,tryfunctions.com
DOMAIN-SUFFIX,windowsazure.com

DOMAIN-SUFFIX,bing
DOMAIN-SUFFIX,bing.com
DOMAIN-SUFFIX,bing.net
DOMAIN-SUFFIX,bingads.com
DOMAIN-SUFFIX,bingagencyawards.com
DOMAIN-SUFFIX,bingapistatistics.com
DOMAIN-SUFFIX,bingsandbox.com
DOMAIN-SUFFIX,bingvisualsearch.com
DOMAIN-SUFFIX,bingworld.com
DOMAIN-SUFFIX,bluehatnights.com
DOMAIN-SUFFIX,dictate.ms
DOMAIN-SUFFIX,flipwithsurface.com
DOMAIN-SUFFIX,masalladeloslimites.com
DOMAIN-SUFFIX,microsoft-give.com
DOMAIN-SUFFIX,microsoftcloudsummit.com
DOMAIN-SUFFIX,microsoftdiplomados.com
DOMAIN-SUFFIX,microsoftlatamholiday.com
DOMAIN-SUFFIX,microsoftmxfilantropia.com
DOMAIN-SUFFIX,microsoftpartnersolutions.com
DOMAIN-SUFFIX,msunlimitedcloudsummit.com
DOMAIN-SUFFIX,office365love.com
DOMAIN-SUFFIX,office365tw.com
DOMAIN-SUFFIX,renovacionoffice.com
DOMAIN-SUFFIX,sprinklesapp.com

DOMAIN-SUFFIX,adaptivecards.io
DOMAIN-SUFFIX,api-extractor.com
DOMAIN-SUFFIX,apisof.net
DOMAIN-SUFFIX,appcenter.ms
DOMAIN-SUFFIX,blazor.net
DOMAIN-SUFFIX,botframework.com
DOMAIN-SUFFIX,codethemicrobit.com
DOMAIN-SUFFIX,devopsassessment.net
DOMAIN-SUFFIX,dot.net
DOMAIN-SUFFIX,gamesstack.com
DOMAIN-SUFFIX,graphengine.io
DOMAIN-SUFFIX,insiderdevtour.com
DOMAIN-SUFFIX,jwt.ms
DOMAIN-SUFFIX,microbit.org
DOMAIN-SUFFIX,microsoftadc.com
DOMAIN-SUFFIX,microsoftgamestack.com
DOMAIN-SUFFIX,microsoftiotinsiderlabs.com
DOMAIN-SUFFIX,microsoftreactor.info
DOMAIN-SUFFIX,microsoftreactor.net
DOMAIN-SUFFIX,microsoftreactor.org
DOMAIN-SUFFIX,microsoftsilverlight.com
DOMAIN-SUFFIX,microsoftsilverlight.org
DOMAIN-SUFFIX,microsoftsilverlight.net
DOMAIN-SUFFIX,microsoftsqlserver.com
DOMAIN-SUFFIX,mmdnn.com
DOMAIN-SUFFIX,mono-project.com
DOMAIN-SUFFIX,msdn.com
DOMAIN-SUFFIX,msinnovationchallenge.com
DOMAIN-SUFFIX,mspairlift.com
DOMAIN-SUFFIX,msropendata.com
DOMAIN-SUFFIX,nuget.org
DOMAIN-SUFFIX,nugettest.org
DOMAIN-SUFFIX,opentranslatorstothings.org
DOMAIN-SUFFIX,poshtestgallery.com
DOMAIN-SUFFIX,pwabuilder.com
DOMAIN-SUFFIX,sankie.net
DOMAIN-SUFFIX,sqlserveronlinux.com
DOMAIN-SUFFIX,timelinestoryteller.com
DOMAIN-SUFFIX,uwpcommunitytoolkit.com
DOMAIN-SUFFIX,visualstudio-staging.com
DOMAIN-SUFFIX,visualstudio.com
DOMAIN-SUFFIX,visualstudio.co
DOMAIN-SUFFIX,visualstudio.co.uk
DOMAIN-SUFFIX,visualstudio.eu
DOMAIN-SUFFIX,visualstudio.net
DOMAIN-SUFFIX,vfsforgit.com
DOMAIN-SUFFIX,vfsforgit.org
DOMAIN-SUFFIX,vsassets.io
DOMAIN-SUFFIX,vscode.dev
DOMAIN-SUFFIX,xamarin.com

DOMAIN-SUFFIX,msocsp.com

DOMAIN-SUFFIX,microsoftnews.cc
DOMAIN-SUFFIX,microsoftnews.com
DOMAIN-SUFFIX,microsoftnews.net
DOMAIN-SUFFIX,microsoftnews.org
DOMAIN-SUFFIX,microsoftnewsforkids.com
DOMAIN-SUFFIX,microsoftnewsforkids.net
DOMAIN-SUFFIX,microsoftnewsforkids.org
DOMAIN-SUFFIX,microsoftnewskids.com
DOMAIN-SUFFIX,microsoftnewskids.net
DOMAIN-SUFFIX,microsoftnewskids.org
DOMAIN-SUFFIX,msn.com
DOMAIN-SUFFIX,msnewskids.com
DOMAIN-SUFFIX,msnewskids.net
DOMAIN-SUFFIX,msnewskids.org
DOMAIN-SUFFIX,msnkids.com

DOMAIN-SUFFIX,1drv.com
DOMAIN-SUFFIX,1drv.ms
DOMAIN-SUFFIX,livefilestore.com
DOMAIN-SUFFIX,onedrive.co
DOMAIN-SUFFIX,onedrive.co.uk
DOMAIN-SUFFIX,onedrive.com
DOMAIN-SUFFIX,onedrive.eu
DOMAIN-SUFFIX,onedrive.net
DOMAIN-SUFFIX,onedrive.org
DOMAIN-SUFFIX,onedrive.live.com
DOMAIN-SUFFIX,storage.live.com

DOMAIN-SUFFIX,forzamotorsport.net
DOMAIN-SUFFIX,forzaracingchampionship.com
DOMAIN-SUFFIX,forzarc.com
DOMAIN-SUFFIX,orithegame.com
DOMAIN-SUFFIX,renovacionxboxlive.com
DOMAIN-SUFFIX,tellmewhygame.com
DOMAIN-SUFFIX,xbox.co
DOMAIN-SUFFIX,xbox.com
DOMAIN-SUFFIX,xbox.eu
DOMAIN-SUFFIX,xbox.org
DOMAIN-SUFFIX,xbox360.co
DOMAIN-SUFFIX,xbox360.com
DOMAIN-SUFFIX,xbox360.eu
DOMAIN-SUFFIX,xbox360.org
DOMAIN-SUFFIX,xboxab.com
DOMAIN-SUFFIX,xboxgamepass.com
DOMAIN-SUFFIX,xboxgamestudios.com
DOMAIN-SUFFIX,xboxlive.com
DOMAIN-SUFFIX,xboxone.co
DOMAIN-SUFFIX,xboxone.com
DOMAIN-SUFFIX,xboxone.eu
DOMAIN-SUFFIX,xboxplayanywhere.com
DOMAIN-SUFFIX,xboxstudios.com
DOMAIN-SUFFIX,xbx.lv

DOMAIN-SUFFIX,microsoft
DOMAIN-SUFFIX,azure
DOMAIN-SUFFIX,hotmail
DOMAIN-SUFFIX,office
DOMAIN-SUFFIX,skype
DOMAIN-SUFFIX,windows
DOMAIN-SUFFIX,xbox
DOMAIN-SUFFIX,microsoft.com
DOMAIN-SUFFIX,femalefounderscomp.com
DOMAIN-SUFFIX,m12.vc
DOMAIN-SUFFIX,aka.ms
DOMAIN-SUFFIX,ankarazirvesi2018.com
DOMAIN-SUFFIX,applicationinsights.io
DOMAIN-SUFFIX,applicationinsights.net
DOMAIN-SUFFIX,aria.ms
DOMAIN-SUFFIX,asp.net
DOMAIN-SUFFIX,aspnetcdn.com
DOMAIN-SUFFIX,binads.com
DOMAIN-SUFFIX,bluehatil.com
DOMAIN-SUFFIX,brazilpartneruniversity.com
DOMAIN-SUFFIX,breakdown.me
DOMAIN-SUFFIX,centralvalidation.com
DOMAIN-SUFFIX,ch9.ms
DOMAIN-SUFFIX,charticulator.com
DOMAIN-SUFFIX,cloudapp.net
DOMAIN-SUFFIX,cloudappsecurity.com
DOMAIN-SUFFIX,cortanaanalytics.com
DOMAIN-SUFFIX,cortanaskills.com
DOMAIN-SUFFIX,crmdynint-gcc.com
DOMAIN-SUFFIX,crmdynint.com
DOMAIN-SUFFIX,crossborderexpansion.com
DOMAIN-SUFFIX,docs.com
DOMAIN-SUFFIX,dynamics.com
DOMAIN-SUFFIX,efproject.net
DOMAIN-SUFFIX,azuredigitaltwin.com
DOMAIN-SUFFIX,fasttrackreadysupport.com
DOMAIN-SUFFIX,fluidpreview.com
DOMAIN-SUFFIX,gameuxmasterguide.com
DOMAIN-SUFFIX,gears5.com
DOMAIN-SUFFIX,gearspop.com
DOMAIN-SUFFIX,gearstactics.com
DOMAIN-SUFFIX,gfx.ms
DOMAIN-SUFFIX,gigjam.com
DOMAIN-SUFFIX,hololens.com
DOMAIN-SUFFIX,hotmail.co
DOMAIN-SUFFIX,hotmail.com
DOMAIN-SUFFIX,hotmail.eu
DOMAIN-SUFFIX,hotmail.net
DOMAIN-SUFFIX,hotmail.org
DOMAIN-SUFFIX,hummingbird.ms
DOMAIN-SUFFIX,ie8.co
DOMAIN-SUFFIX,ie9.com
DOMAIN-SUFFIX,ie10.com
DOMAIN-SUFFIX,ie11.com
DOMAIN-SUFFIX,internetexplorer.co
DOMAIN-SUFFIX,internetexplorer.com
DOMAIN-SUFFIX,imaginecup.pl
DOMAIN-SUFFIX,ingads.com
DOMAIN-SUFFIX,intunewiki.com
DOMAIN-SUFFIX,iotinactionevents.com
DOMAIN-SUFFIX,kidgrid.tv
DOMAIN-SUFFIX,latampartneruniversity.com
DOMAIN-SUFFIX,live.com
DOMAIN-SUFFIX,live.com.au
DOMAIN-SUFFIX,live.eu
DOMAIN-SUFFIX,live.net
DOMAIN-SUFFIX,livingyourambition.com
DOMAIN-SUFFIX,makecode.org
DOMAIN-SUFFIX,managedmeetingrooms.com
DOMAIN-SUFFIX,meetfasttrack.com
DOMAIN-SUFFIX,meetyourdevices.com
DOMAIN-SUFFIX,mepn.com
DOMAIN-SUFFIX,microsoft-int.com
DOMAIN-SUFFIX,microsoft-ppe.com
DOMAIN-SUFFIX,microsoft-sap-events.com
DOMAIN-SUFFIX,microsoft-sbs-domains.com
DOMAIN-SUFFIX,microsoft365.com
DOMAIN-SUFFIX,microsoftaccountguard.com
DOMAIN-SUFFIX,microsoftads.com
DOMAIN-SUFFIX,microsoftadvertising.com
DOMAIN-SUFFIX,microsoftadvertisingregionalawards.com
DOMAIN-SUFFIX,microsoftaffiliates.com
DOMAIN-SUFFIX,microsoftcloud.com
DOMAIN-SUFFIX,microsoftcloudworkshop.com
DOMAIN-SUFFIX,microsoftcommunitytraining.com
DOMAIN-SUFFIX,microsoftedge.com
DOMAIN-SUFFIX,microsofthouse.com
DOMAIN-SUFFIX,microsofthouse.net
DOMAIN-SUFFIX,microsoftinternetsafety.net
DOMAIN-SUFFIX,microsoftlatamaitour.com
DOMAIN-SUFFIX,microsoftlinc.com
DOMAIN-SUFFIX,microsoftonline-p.com
DOMAIN-SUFFIX,microsoftonline.com
DOMAIN-SUFFIX,microsoftpartnercommunity.com
DOMAIN-SUFFIX,microsoftready.com
DOMAIN-SUFFIX,microsoftsiteselection.com
DOMAIN-SUFFIX,microsoftstore.com
DOMAIN-SUFFIX,microsoftstore.com.hk
DOMAIN-SUFFIX,microsoftstream.com
DOMAIN-SUFFIX,microsoftteams.com
DOMAIN-SUFFIX,microsofttradein.com
DOMAIN-SUFFIX,microsofttranslator.com
DOMAIN-SUFFIX,microsoftuwp.com
DOMAIN-SUFFIX,momentumms.com
DOMAIN-SUFFIX,morphcharts.com
DOMAIN-SUFFIX,mpnevolution.com
DOMAIN-SUFFIX,ms-studiosmedia.com
DOMAIN-SUFFIX,ms365surfaceoffer.com
DOMAIN-SUFFIX,msads.net
DOMAIN-SUFFIX,msauth.net
DOMAIN-SUFFIX,mschallenge2018.com
DOMAIN-SUFFIX,msecnd.net
DOMAIN-SUFFIX,msedge.net
DOMAIN-SUFFIX,msft.info
DOMAIN-SUFFIX,msft.net
DOMAIN-SUFFIX,msftauth.net
DOMAIN-SUFFIX,msfteducation.ca
DOMAIN-SUFFIX,msftnet.org
DOMAIN-SUFFIX,msgamesresearch.com
DOMAIN-SUFFIX,msocdn.com
DOMAIN-SUFFIX,msturing.org
DOMAIN-SUFFIX,msudalosti.com
DOMAIN-SUFFIX,mymicrosoft.com
DOMAIN-SUFFIX,nextechafrica.net
DOMAIN-SUFFIX,nxta.org
DOMAIN-SUFFIX,o365weve-dev.com
DOMAIN-SUFFIX,o365weve-ppe.com
DOMAIN-SUFFIX,o365weve.com
DOMAIN-SUFFIX,office.com
DOMAIN-SUFFIX,office.net
DOMAIN-SUFFIX,office365.com
DOMAIN-SUFFIX,onenote.com
DOMAIN-SUFFIX,onenote.net
DOMAIN-SUFFIX,onestore.ms
DOMAIN-SUFFIX,opticsforthecloud.net
DOMAIN-SUFFIX,outingsapp.com
DOMAIN-SUFFIX,outlook.com
DOMAIN-SUFFIX,passport.net
DOMAIN-SUFFIX,pixapp.net
DOMAIN-SUFFIX,powerappscdn.net
DOMAIN-SUFFIX,powerautomate.com
DOMAIN-SUFFIX,powerbi.com
DOMAIN-SUFFIX,powershellgallery.com
DOMAIN-SUFFIX,projectmurphy.net
DOMAIN-SUFFIX,projectsangam.com
DOMAIN-SUFFIX,pxt.io
DOMAIN-SUFFIX,s-microsoft.com
DOMAIN-SUFFIX,s-msn.com
DOMAIN-SUFFIX,sfbassets.com
DOMAIN-SUFFIX,sfbassets.net
DOMAIN-SUFFIX,sfx.ms
DOMAIN-SUFFIX,sharepoint.com
DOMAIN-SUFFIX,sharepointonline.com
DOMAIN-SUFFIX,skype.com
DOMAIN-SUFFIX,skype.net
DOMAIN-SUFFIX,skypeassets.com
DOMAIN-SUFFIX,skypeassets.net
DOMAIN-SUFFIX,staffhub.ms
DOMAIN-SUFFIX,successwithteams.com
DOMAIN-SUFFIX,surface.com
DOMAIN-SUFFIX,svc.ms
DOMAIN-SUFFIX,sway-cdn.com
DOMAIN-SUFFIX,sway.com
DOMAIN-SUFFIX,sysinternals.com
DOMAIN-SUFFIX,tailwindtraders.com
DOMAIN-SUFFIX,techhub.ms
DOMAIN-SUFFIX,tfsallin.net
DOMAIN-SUFFIX,trafficmanager.net
DOMAIN-SUFFIX,translatetheweb.com
DOMAIN-SUFFIX,unlocklimitlesslearning.com
DOMAIN-SUFFIX,userpxt.io
DOMAIN-SUFFIX,videobreakdown.com
DOMAIN-SUFFIX,videoindexer.ai
DOMAIN-SUFFIX,virtualearth.net
DOMAIN-SUFFIX,vsallin.net
DOMAIN-SUFFIX,wbd.ms
DOMAIN-SUFFIX,what-fan.net
DOMAIN-SUFFIX,windows-int.net
DOMAIN-SUFFIX,windows.com
DOMAIN-SUFFIX,windows.net
DOMAIN-SUFFIX,windows.nl
DOMAIN-SUFFIX,windows8.hk
DOMAIN-SUFFIX,windowscommunity.net
DOMAIN-SUFFIX,windowsmarketplace.com
DOMAIN-SUFFIX,windowsphone-int.com
DOMAIN-SUFFIX,windowsphone.com
DOMAIN-SUFFIX,windowssearch.com
DOMAIN-SUFFIX,windowsupdate.com
DOMAIN-SUFFIX,winhec.com
DOMAIN-SUFFIX,winhec.net
DOMAIN-SUFFIX,yammer.com

# > Amazon
DOMAIN-SUFFIX,amazon
DOMAIN-SUFFIX,xn--cckwcxetd
DOMAIN-SUFFIX,xn--jlq480n2rg
DOMAIN-SUFFIX,yamaxun
DOMAIN-SUFFIX,zappos
DOMAIN-SUFFIX,a2z.com
DOMAIN-SUFFIX,aboutamazon.com
DOMAIN-SUFFIX,amaaozn.com
DOMAIN-SUFFIX,amazon-fashions.com
DOMAIN-SUFFIX,amazon-jp-recruiting.com
DOMAIN-SUFFIX,amazon-lantern.com
DOMAIN-SUFFIX,amazon-launchpad.com
DOMAIN-SUFFIX,amazon.com
DOMAIN-SUFFIX,amazon.sg
DOMAIN-SUFFIX,amazonalexavoxcon.com
DOMAIN-SUFFIX,amazonauthorinsights.com
DOMAIN-SUFFIX,amazonbusiness.org
DOMAIN-SUFFIX,amazonbusinessblog.com
DOMAIN-SUFFIX,amazondevicesupport.com
DOMAIN-SUFFIX,amazonfctours.com
DOMAIN-SUFFIX,amazonianblog.com
DOMAIN-SUFFIX,amazonimages.com
DOMAIN-SUFFIX,amazonlaunchpad.com
DOMAIN-SUFFIX,amazonliterarypartnership.com
DOMAIN-SUFFIX,amazonlumberyard.wang
DOMAIN-SUFFIX,amazonpay.com
DOMAIN-SUFFIX,amazonsdi.com
DOMAIN-SUFFIX,amazonstudiosguilds.com
DOMAIN-SUFFIX,amazonvideodirect.com
DOMAIN-SUFFIX,amzn.asia
DOMAIN-SUFFIX,amzn.com
DOMAIN-SUFFIX,amzn.to
DOMAIN-SUFFIX,amznl.com
DOMAIN-SUFFIX,associates-amazon.com
DOMAIN-SUFFIX,gameon-masters.com
DOMAIN-SUFFIX,gdansk-amazon.com
DOMAIN-SUFFIX,images-amazon.com
DOMAIN-SUFFIX,media-amazon.com
DOMAIN-SUFFIX,primeday.info
DOMAIN-SUFFIX,siege-amazon.com
DOMAIN-SUFFIX,ssl-images-amazon.com
DOMAIN-SUFFIX,ueberamazon.de
DOMAIN-SUFFIX,yamaxun.com
DOMAIN-SUFFIX,alexa.com
DOMAIN-SUFFIX,audible.com
DOMAIN-SUFFIX,createspace.com

# > Cloudflare
DOMAIN-SUFFIX,cloudflare-dns.com
DOMAIN-SUFFIX,cloudflare-ipfs.com
DOMAIN-SUFFIX,cf-ipfs.com
DOMAIN-SUFFIX,cloudflare-quic.com
DOMAIN-SUFFIX,cloudflare.com
DOMAIN-SUFFIX,cloudflare.net
DOMAIN-SUFFIX,cloudflareapps.com
DOMAIN-SUFFIX,cloudflarebolt.com
DOMAIN-SUFFIX,cloudflareclient.com
DOMAIN-SUFFIX,cloudflareinsights.com
DOMAIN-SUFFIX,cloudflareok.com
DOMAIN-SUFFIX,cloudflareresolve.com
DOMAIN-SUFFIX,cloudflaressl.com
DOMAIN-SUFFIX,cloudflarestatus.com
DOMAIN-SUFFIX,cloudflarestream.com
DOMAIN-SUFFIX,cloudflaretest.com
DOMAIN-SUFFIX,cloudflarewarp.com
DOMAIN-SUFFIX,one.one.one
DOMAIN-SUFFIX,pacloudflare.com
DOMAIN-SUFFIX,pages.dev
DOMAIN-SUFFIX,trycloudflare.com
DOMAIN-SUFFIX,videodelivery.net
DOMAIN-SUFFIX,warp.plus
DOMAIN-SUFFIX,workers.dev

# > Akamai
DOMAIN-SUFFIX,ak1.net
DOMAIN-SUFFIX,aka-ai.com
DOMAIN-SUFFIX,aka-ai.net
DOMAIN-SUFFIX,akacrypto.net
DOMAIN-SUFFIX,akadeem.net
DOMAIN-SUFFIX,akadns.com
DOMAIN-SUFFIX,akadns6.net
DOMAIN-SUFFIX,akaeai.com
DOMAIN-SUFFIX,akafms.net
DOMAIN-SUFFIX,akahost.net
DOMAIN-SUFFIX,akaint.net
DOMAIN-SUFFIX,akam.net
DOMAIN-SUFFIX,akamaa.com
DOMAIN-SUFFIX,akamah.com
DOMAIN-SUFFIX,akamak.com
DOMAIN-SUFFIX,akamam.com
DOMAIN-SUFFIX,akamai-access.com
DOMAIN-SUFFIX,akamai-access.net
DOMAIN-SUFFIX,akamai-cdn.com
DOMAIN-SUFFIX,akamai-platform-internal.net
DOMAIN-SUFFIX,akamai-platform-staging.com
DOMAIN-SUFFIX,akamai-platform.net
DOMAIN-SUFFIX,akamai-regression.net
DOMAIN-SUFFIX,akamai-staging.net
DOMAIN-SUFFIX,akamai-sucks.net
DOMAIN-SUFFIX,akamai-thailand.com
DOMAIN-SUFFIX,akamai-thailand.net
DOMAIN-SUFFIX,akamai-trials.com
DOMAIN-SUFFIX,akamai.co.kr
DOMAIN-SUFFIX,akamai.com
DOMAIN-SUFFIX,akamai.net
DOMAIN-SUFFIX,akamaientrypoint.net
DOMAIN-SUFFIX,akamaietpcnctest.com
DOMAIN-SUFFIX,akamaietpcompromisedcnctest.com
DOMAIN-SUFFIX,akamaietpcompromisedmalwaretest.com
DOMAIN-SUFFIX,akamaietpmalwaretest.com
DOMAIN-SUFFIX,akamaietpphishingtest.com
DOMAIN-SUFFIX,akamaihd-staging.net
DOMAIN-SUFFIX,akamaihd.com
DOMAIN-SUFFIX,akamaihd.net
DOMAIN-SUFFIX,akamaimagicmath.net
DOMAIN-SUFFIX,akamainewzealand.com
DOMAIN-SUFFIX,akamaiphillipines.com
DOMAIN-SUFFIX,akamaiphillipines.net
DOMAIN-SUFFIX,akamaitech.com
DOMAIN-SUFFIX,akamaitech.net
DOMAIN-SUFFIX,akamaitechnologies.com
DOMAIN-SUFFIX,akamaitechnologies.net
DOMAIN-SUFFIX,akamaisingapore.net
DOMAIN-SUFFIX,akamaized-staging.net
DOMAIN-SUFFIX,akamaized.net
DOMAIN-SUFFIX,akamaizercentral.com
DOMAIN-SUFFIX,akamci.com
DOMAIN-SUFFIX,akami.com
DOMAIN-SUFFIX,akami.net
DOMAIN-SUFFIX,akamii.com
DOMAIN-SUFFIX,akamqi.com
DOMAIN-SUFFIX,akastream.com
DOMAIN-SUFFIX,akastream.net
DOMAIN-SUFFIX,akatns.net
DOMAIN-SUFFIX,iamakamai.com
DOMAIN-SUFFIX,iamakamai.net
DOMAIN-SUFFIX,soasta-dswb.com
DOMAIN-SUFFIX,srtcdn.net

# > Fastly
DOMAIN-SUFFIX,fastly.com
DOMAIN-SUFFIX,fastly.net
DOMAIN-SUFFIX,fastlylabs.com
DOMAIN-SUFFIX,fastlylb.net
DOMAIN-SUFFIX,fastly-terrarium.com
DOMAIN-SUFFIX,zencdn.net

# > Fastly
DOMAIN-SUFFIX,stackpath.com
DOMAIN-SUFFIX,stackpath.dev

# > AWS
DOMAIN-SUFFIX,aws
DOMAIN-SUFFIX,acmvalidations.com
DOMAIN-SUFFIX,acmvalidationsaws.com
DOMAIN-SUFFIX,aesworkshops.com
DOMAIN-SUFFIX,amazonaws-china.com
DOMAIN-SUFFIX,amazonaws.co.uk
DOMAIN-SUFFIX,amazonaws.com
DOMAIN-SUFFIX,amazonaws.tv
DOMAIN-SUFFIX,amazonworkdocs.com
DOMAIN-SUFFIX,amplifyapp.com
DOMAIN-SUFFIX,amplifyframework.com
DOMAIN-SUFFIX,aws-iot-hackathon.com
DOMAIN-SUFFIX,awsautopilot.com
DOMAIN-SUFFIX,awsautoscaling.com
DOMAIN-SUFFIX,awsbraket.com
DOMAIN-SUFFIX,awscommandlineinterface.com
DOMAIN-SUFFIX,awsedstart.com
DOMAIN-SUFFIX,awseducate.com
DOMAIN-SUFFIX,awseducate.net
DOMAIN-SUFFIX,awseducate.org
DOMAIN-SUFFIX,awsglobalaccelerator.com
DOMAIN-SUFFIX,awsloft-johannesburg.com
DOMAIN-SUFFIX,awsloft-stockholm.com
DOMAIN-SUFFIX,awssecworkshops.com
DOMAIN-SUFFIX,awsstatic.com
DOMAIN-SUFFIX,awsthinkbox.com
DOMAIN-SUFFIX,cdkworkshop.com
DOMAIN-SUFFIX,cloudfront.net
DOMAIN-SUFFIX,containersonaws.com
DOMAIN-SUFFIX,elasticbeanstalk.com
DOMAIN-SUFFIX,thinkboxsoftware.com
  
# > PayPal
DOMAIN-KEYWORD,paypal
DOMAIN-SUFFIX,paypal.com
DOMAIN-SUFFIX,paypalobjects.com

# > Netflix
DOMAIN-SUFFIX,fast.com
DOMAIN-SUFFIX,netflix.ca
DOMAIN-SUFFIX,netflix.com
DOMAIN-SUFFIX,netflix.net
DOMAIN-SUFFIX,netflixinvestor.com
DOMAIN-SUFFIX,netflixtechblog.com
DOMAIN-SUFFIX,nflxext.com
DOMAIN-SUFFIX,nflximg.com
DOMAIN-SUFFIX,nflximg.net
DOMAIN-SUFFIX,nflxsearch.net
DOMAIN-SUFFIX,nflxso.net
DOMAIN-SUFFIX,nflxvideo.net

DOMAIN-SUFFIX,netflixdnstest1.com
DOMAIN-SUFFIX,netflixdnstest2.com
DOMAIN-SUFFIX,netflixdnstest3.com
DOMAIN-SUFFIX,netflixdnstest4.com
DOMAIN-SUFFIX,netflixdnstest5.com
DOMAIN-SUFFIX,netflixdnstest6.com
DOMAIN-SUFFIX,netflixdnstest7.com
DOMAIN-SUFFIX,netflixdnstest8.com
DOMAIN-SUFFIX,netflixdnstest9.com
DOMAIN-SUFFIX,netflixdnstest10.com

DOMAIN-SUFFIX,amazonaws.com
DOMAIN-SUFFIX,akamaiedge.net
DOMAIN-SUFFIX,cookielaw.org

DOMAIN,netflix.com.edgesuite.net
  
DOMAIN-KEYWORD,netflixdnstest
DOMAIN-KEYWORD,dualstack.apiproxy-
DOMAIN-KEYWORD,dualstack.ichnaea-web-
DOMAIN-KEYWORD,apiproxy-device-prod-nlb-

IP-CIDR,23.246.0.0/18,no-resolve
IP-CIDR,37.77.184.0/21,no-resolve
IP-CIDR,38.72.126.0/24,no-resolve
IP-CIDR,45.57.0.0/17,no-resolve
IP-CIDR,64.120.128.0/17,no-resolve
IP-CIDR,66.197.128.0/17,no-resolve
IP-CIDR,69.53.224.0/19,no-resolve
IP-CIDR,103.87.204.0/22,no-resolve
IP-CIDR,108.175.32.0/20,no-resolve
IP-CIDR,185.2.220.0/22,no-resolve
IP-CIDR,185.9.188.0/22,no-resolve
IP-CIDR,192.173.64.0/18,no-resolve
IP-CIDR,198.38.96.0/19,no-resolve
IP-CIDR,198.45.48.0/20,no-resolve
IP-CIDR,208.75.76.0/22,no-resolve
IP-CIDR,34.210.42.111/32,no-resolve
IP-CIDR,52.89.124.203/32,no-resolve
IP-CIDR,54.148.37.5/32,no-resolve

IP-CIDR,8.8.8.8/32,no-resolve
IP-CIDR,8.8.4.4/32,no-resolve

# > Disney Plus
DOMAIN-SUFFIX,abc-studios.com
DOMAIN-SUFFIX,abc.com
DOMAIN-SUFFIX,edgedatg.com

DOMAIN-SUFFIX,bamgrid.com
DOMAIN-SUFFIX,dmed.technology

DOMAIN-SUFFIX,dtci.co
DOMAIN-SUFFIX,dtci.technology
DOMAIN-SUFFIX,espn.co.uk
DOMAIN-SUFFIX,espn.com
DOMAIN-SUFFIX,espn.net
DOMAIN-SUFFIX,espncdn.com
DOMAIN-SUFFIX,espnqa.com
DOMAIN-SUFFIX,watchespn.com
DOMAIN-SUFFIX,omtrdc.net

DOMAIN-SUFFIX,marvel.com
DOMAIN-SUFFIX,marvel10thanniversary.com
DOMAIN-SUFFIX,marveldimensionofheroes.com
DOMAIN-SUFFIX,marvelparty.net
DOMAIN-SUFFIX,marvelpinball.com
DOMAIN-SUFFIX,marvelsdoubleagent.com
DOMAIN-SUFFIX,marvelspotlightplays.com
DOMAIN-SUFFIX,marvelsuperheroseptember.com
DOMAIN-SUFFIX,marvelsuperwar.com
DOMAIN-SUFFIX,themarvelexperiencetour.com

DOMAIN-SUFFIX,natgeomaps.com
DOMAIN-SUFFIX,nationalgeographic.com
DOMAIN-SUFFIX,nationalgeographicpartners.com
DOMAIN-SUFFIX,ngeo.com

DOMAIN-SUFFIX,disney.asia
DOMAIN-SUFFIX,disney.co.jp
DOMAIN-SUFFIX,disney.co.kr
DOMAIN-SUFFIX,disney.com
DOMAIN-SUFFIX,disney.sg
DOMAIN-SUFFIX,20thcenturystudios.com.au
DOMAIN-SUFFIX,20thcenturystudios.com.br
DOMAIN-SUFFIX,20thcenturystudios.jp
DOMAIN-SUFFIX,adventuresbydisney.com
DOMAIN-SUFFIX,babble.com
DOMAIN-SUFFIX,babyzone.com
DOMAIN-SUFFIX,bamgrid.com
DOMAIN-SUFFIX,beautyandthebeastmusical.co.uk
DOMAIN-SUFFIX,dilcdn.com
DOMAIN-SUFFIX,disney-asia.com
DOMAIN-SUFFIX,disney-discount.com
DOMAIN-SUFFIX,disney-plus.net
DOMAIN-SUFFIX,disney-portal.my.onetrust.com
DOMAIN-SUFFIX,disney-studio.com
DOMAIN-SUFFIX,disney-studio.net
DOMAIN-SUFFIX,disney.my.sentry.io
DOMAIN-SUFFIX,disneyadsales.com
DOMAIN-SUFFIX,disneyarena.com
DOMAIN-SUFFIX,disneyaulani.com
DOMAIN-SUFFIX,disneybaby.com
DOMAIN-SUFFIX,disneycareers.com
DOMAIN-SUFFIX,disneychannelonstage.com
DOMAIN-SUFFIX,disneychannelroadtrip.com
DOMAIN-SUFFIX,disneycruisebrasil.com
DOMAIN-SUFFIX,disneyenconcert.com
DOMAIN-SUFFIX,disneyiejobs.com
DOMAIN-SUFFIX,disneyinflight.com
DOMAIN-SUFFIX,disneyinternational.com
DOMAIN-SUFFIX,disneyinternationalhd.com
DOMAIN-SUFFIX,disneyjunior.com
DOMAIN-SUFFIX,disneyjuniortreataday.com
DOMAIN-SUFFIX,disneylatino.com
DOMAIN-SUFFIX,disneymagicmomentsme.com
DOMAIN-SUFFIX,disneyme.com
DOMAIN-SUFFIX,disneymeetingsandevents.com
DOMAIN-SUFFIX,disneymovieinsiders.com
DOMAIN-SUFFIX,disneymusicpromotion.com
DOMAIN-SUFFIX,disneynewseries.com
DOMAIN-SUFFIX,disneynow.com
DOMAIN-SUFFIX,disneypeoplesurveys.com
DOMAIN-SUFFIX,disneyplus.bn5x.net
DOMAIN-SUFFIX,disneyplus.com
DOMAIN-SUFFIX,disneyplus.com.ssl.sc.omtrdc.net
DOMAIN-SUFFIX,disneyredirects.com
DOMAIN-SUFFIX,disneysrivieraresort.com
DOMAIN-SUFFIX,disneystore.com
DOMAIN-SUFFIX,disneystreaming.com
DOMAIN-SUFFIX,disneysubscription.com
DOMAIN-SUFFIX,disneytickets.co.uk
DOMAIN-SUFFIX,disneyturkiye.com.tr
DOMAIN-SUFFIX,disneytvajobs.com
DOMAIN-SUFFIX,disneyworld-go.com
DOMAIN-SUFFIX,dssott.com
DOMAIN-SUFFIX,go-disneyworldgo.com
DOMAIN-SUFFIX,go.com
DOMAIN-SUFFIX,mickey.tv
DOMAIN-SUFFIX,moviesanywhere.com
DOMAIN-SUFFIX,nomadlandmovie.ch
DOMAIN-SUFFIX,playmation.com
DOMAIN-SUFFIX,shopdisney.com
DOMAIN-SUFFIX,shops-disney.com
DOMAIN-SUFFIX,sorcerersarena.com
DOMAIN-SUFFIX,spaindisney.com
DOMAIN-SUFFIX,star-brasil.com
DOMAIN-SUFFIX,star-latam.com
DOMAIN-SUFFIX,starwars.com
DOMAIN-SUFFIX,starwarsgalacticstarcruiser.com
DOMAIN-SUFFIX,starwarskids.com
DOMAIN-SUFFIX,streamingdisney.net
DOMAIN-SUFFIX,thestationbymaker.com
DOMAIN-SUFFIX,thisispolaris.com
DOMAIN-SUFFIX,watchdisneyfe.com

DOMAIN-SUFFIX,braze.com
DOMAIN-SUFFIX,cdn.optimizely.com
DOMAIN-SUFFIX,cdn.registerdisney.go.com
DOMAIN-SUFFIX,cws.conviva.com
DOMAIN-SUFFIX,d9.flashtalking.com
DOMAIN-SUFFIX,disney.demdex.net
DOMAIN-SUFFIX,js-agent.newrelic.com

# > CAs
DOMAIN-SUFFIX,actalis.com
DOMAIN-SUFFIX,actalis.it

DOMAIN-SUFFIX,amazontrust.com
DOMAIN-SUFFIX,awstrust.com
DOMAIN-SUFFIX,ss2.us

DOMAIN-SUFFIX,buypass-ssl.com
DOMAIN-SUFFIX,buypass.com
DOMAIN-SUFFIX,buypass.no
DOMAIN-SUFFIX,buypass.se
DOMAIN-SUFFIX,minid.no

DOMAIN-SUFFIX,certum.pl
DOMAIN-SUFFIX,ocsp-certum.com

DOMAIN-SUFFIX,comodo.com
DOMAIN-SUFFIX,comodo.net
DOMAIN-SUFFIX,comodoca.com
DOMAIN-SUFFIX,comodoca2.com
DOMAIN-SUFFIX,comodoca3.com
DOMAIN-SUFFIX,comodoca4.com

DOMAIN-SUFFIX,cybertrust.co.jp
DOMAIN-SUFFIX,cybertrust.ne.jp

DOMAIN-SUFFIX,digicert-cn.com
DOMAIN-SUFFIX,digicert.com
DOMAIN-SUFFIX,digitalcertvalidation.com
DOMAIN-SUFFIX,freessl.com
DOMAIN-SUFFIX,geotrust.com
DOMAIN-SUFFIX,rapidssl.com
DOMAIN-SUFFIX,thawte.com
DOMAIN-SUFFIX,thawte.de
DOMAIN-SUFFIX,thawte.fr

DOMAIN-SUFFIX,entrust.net
DOMAIN-SUFFIX,entrustdatacard.com

DOMAIN-SUFFIX,alphassl.com
DOMAIN-SUFFIX,globalsign-media.com
DOMAIN-SUFFIX,globalsign.be
DOMAIN-SUFFIX,globalsign.ch
DOMAIN-SUFFIX,globalsign.co.uk
DOMAIN-SUFFIX,globalsign.com
DOMAIN-SUFFIX,globalsign.com.au
DOMAIN-SUFFIX,globalsign.com.hk
DOMAIN-SUFFIX,globalsign.com.sg
DOMAIN-SUFFIX,globalsign.es
DOMAIN-SUFFIX,globalsign.eu
DOMAIN-SUFFIX,globalsign.fr
DOMAIN-SUFFIX,globalsign.net
DOMAIN-SUFFIX,globalsign.nl

DOMAIN-SUFFIX,godaddy.com
DOMAIN-SUFFIX,godaddy

DOMAIN-SUFFIX,pki.goog

DOMAIN-SUFFIX,eca.hinet.net
DOMAIN-SUFFIX,gtlsca.nat.gov.tw

DOMAIN-SUFFIX,hongkongpost.gov.hk
DOMAIN-SUFFIX,ecert.gov.hk

DOMAIN-SUFFIX,identrust.com
DOMAIN-SUFFIX,identrust.co.uk
DOMAIN-SUFFIX,identrust.net

DOMAIN-SUFFIX,lencr.org
DOMAIN-SUFFIX,letsencrypt.org

DOMAIN-SUFFIX,msocsp.com

DOMAIN-SUFFIX,secom.co.jp
DOMAIN-SUFFIX,secomtrust.net

DOMAIN-SUFFIX,enterprisessl.com
DOMAIN-SUFFIX,hackerguardian.com
DOMAIN-SUFFIX,instantssl.com
DOMAIN-SUFFIX,optimumssl.com
DOMAIN-SUFFIX,positivessl.com
DOMAIN-SUFFIX,sectigo.com
DOMAIN-SUFFIX,trust-provider.cn @cn
DOMAIN-SUFFIX,trust-provider.com
DOMAIN-SUFFIX,usertrust.com

DOMAIN-SUFFIX,ssl.com

DOMAIN-SUFFIX,digital-id.ch
DOMAIN-SUFFIX,digitalid.ch
DOMAIN-SUFFIX,managed-pki.ch
DOMAIN-SUFFIX,managed-pki.de
DOMAIN-SUFFIX,pki-post.ch
DOMAIN-SUFFIX,pki-posta.ch
DOMAIN-SUFFIX,pki-poste.ch
DOMAIN-SUFFIX,root-signing.ch
DOMAIN-SUFFIX,rootsigning.com
DOMAIN-SUFFIX,ssl-certificate.ch
DOMAIN-SUFFIX,swissid.ch
DOMAIN-SUFFIX,swissign.com
DOMAIN-SUFFIX,swissign.li
DOMAIN-SUFFIX,swisssign-group.ch
DOMAIN-SUFFIX,swisssign-group.com
DOMAIN-SUFFIX,swisssign-group.li
DOMAIN-SUFFIX,swisssign.ch
DOMAIN-SUFFIX,swisssign.com
DOMAIN-SUFFIX,swisssign.li
DOMAIN-SUFFIX,swisssign.net
DOMAIN-SUFFIX,swisssign.org
DOMAIN-SUFFIX,swisssigner.ch
DOMAIN-SUFFIX,swisssigner.com
DOMAIN-SUFFIX,swisssigngroup.ch
DOMAIN-SUFFIX,swisssigngroup.com
DOMAIN-SUFFIX,swissstick.com
DOMAIN-SUFFIX,swisstsa.ch
DOMAIN-SUFFIX,swisstsa.li
DOMAIN-SUFFIX,trustdoc.ch
DOMAIN-SUFFIX,trustsign.ch
DOMAIN-SUFFIX,zert.ch

DOMAIN-SUFFIX,telekom.com
DOMAIN-SUFFIX,telekom.de

DOMAIN-SUFFIX,trustwave.com

DOMAIN-SUFFIX,twca.com.tw

DOMAIN-SUFFIX,verisign.asia
DOMAIN-SUFFIX,verisign.biz
DOMAIN-SUFFIX,verisign.ch
DOMAIN-SUFFIX,verisign.co.in
DOMAIN-SUFFIX,verisign.co.uk
DOMAIN-SUFFIX,verisign.com
DOMAIN-SUFFIX,verisign.com.au
DOMAIN-SUFFIX,verisign.com.br
DOMAIN-SUFFIX,verisign.com.cn
DOMAIN-SUFFIX,verisign.com.es
DOMAIN-SUFFIX,verisign.com.hk
DOMAIN-SUFFIX,verisign.com.sg
DOMAIN-SUFFIX,verisign.com.tw
DOMAIN-SUFFIX,verisign.com.vn
DOMAIN-SUFFIX,verisign.de
DOMAIN-SUFFIX,verisign.dk
DOMAIN-SUFFIX,verisign.es
DOMAIN-SUFFIX,verisign.fr
DOMAIN-SUFFIX,verisign.hk
DOMAIN-SUFFIX,verisign.in
DOMAIN-SUFFIX,verisign.info
DOMAIN-SUFFIX,verisign.jobs
DOMAIN-SUFFIX,verisign.mobi
DOMAIN-SUFFIX,verisign.name
DOMAIN-SUFFIX,verisign.net
DOMAIN-SUFFIX,verisign.org
DOMAIN-SUFFIX,verisign.pro
DOMAIN-SUFFIX,verisign.se
DOMAIN-SUFFIX,verisign.sg
DOMAIN-SUFFIX,verisign.tw
DOMAIN-SUFFIX,verisign.us
DOMAIN-SUFFIX,verisign.vn
DOMAIN-SUFFIX,verisigninc.com

# > Other
DOMAIN-KEYWORD,appledaily
DOMAIN-KEYWORD,beetalk
DOMAIN-KEYWORD,blogspot
DOMAIN-KEYWORD,dropbox
DOMAIN-KEYWORD,facebook
DOMAIN-KEYWORD,github
DOMAIN-KEYWORD,instagram
DOMAIN-KEYWORD,twitter
DOMAIN-KEYWORD,whatsapp
DOMAIN-KEYWORD,google
DOMAIN-KEYWORD,telegram
